// Actual hosted WASM, real strict CP root/policy signatures; TEST-only public
// fixture generated by attachment-stream-fixture.rs. No provider/DB/LAB effects.
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { decode, encode } from "../../../packages/sdk/src/cbor.ts";
import { verifyHostedGenesis } from "../src/keygen.ts";
import { HostedCustody } from "../src/custody/hosted-custody.ts";
import { encodeEnvelope } from "../src/custody/envelope.ts";
const f = JSON.parse(readFileSync(new URL("./fixtures/public-genesis.json", import.meta.url)));
const pins = new Uint8Array(Buffer.from(f.pins, "base64")), item = new Uint8Array(Buffer.from(f.item, "base64")), hash = new Uint8Array(Buffer.from(f.sha256, "hex"));
const module = new WebAssembly.Module(readFileSync(new URL("../hosted.wasm", import.meta.url)));
const roots = decode(pins)[0].map(r => r[1]);

test("actual engine-less WASM validates original strict signed genesis without SQL/key capabilities", () => {
  assert.equal(verifyHostedGenesis(module, f.collection, pins, item, hash), true);
  assert.equal(verifyHostedGenesis(module, "00000000-0000-0000-0000-000000000001", pins, item, hash), false);
  assert.equal(verifyHostedGenesis(module, f.collection, pins, item, new Uint8Array(32)), false);
  assert.equal(verifyHostedGenesis(module, f.collection, new Uint8Array(), item, hash), false);
  const p = decode(pins); p[1] = [];
  assert.equal(verifyHostedGenesis(module, f.collection, encode(p), item, hash), false);
});

test("actual WASM native refusal causes zero KMS/derive/token effects", async () => {
  const arn = "arn:aws:kms:us-east-1:000000000000:key/11111111-1111-4111-8111-111111111111";
  const device = "66666666-6666-6666-6666-666666666666";
  let unwraps = 0, derives = 0, issues = 0;
  const record = {kind: "hosted", deviceId: device, signPk: new Uint8Array(32).fill(1), kemPk: new Uint8Array(32).fill(2), noisePk: new Uint8Array(32).fill(3),
    wrappedKeys: encodeEnvelope(arn, Uint8Array.of(1)), kmsKeyArn: arn, genesis: {seq: 1, item, hash: new Uint8Array(32)} };
  const c = new HostedCustody({collection: f.collection, replicaId: f.collection, keyArn: arn, roots, policyPins: pins, signers: [device]},
    {serviceDevice: async () => record, logToken: async () => {issues++; throw new Error();}, forget: () => {}},
    {unwrapDeviceKeys: async () => {unwraps++; throw new Error();}}, () => {derives++; return null;},
    (collection, p, i, h) => verifyHostedGenesis(module, collection, p, i, h));
  await assert.rejects(c.openSealer(f.collection, new AbortController().signal), /custody_invalid_record/);
  await assert.rejects(c.logToken(f.collection, new AbortController().signal));
  assert.equal(unwraps + derives + issues, 0);
});
