version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      npm-development:
        dependency-type: development
      npm-production:
        dependency-type: production
    open-pull-requests-limit: 10

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      workflow-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: weekly
      day: monday
    groups:
      container-images:
        patterns:
          - "*"
    open-pull-requests-limit: 5
