import { webcrypto } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import { AppIndexedDbDeviceKeyProvider } from "../src/app-host/device-key-provider.js";
const origin="https://app.example.test",crypto=webcrypto as unknown as Crypto;
async function fixture(){
  const sample=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);
  vi.stubGlobal("crypto",crypto);vi.stubGlobal("CryptoKey",sample.constructor);vi.stubGlobal("location",{origin});
  const state={exists:false,value:undefined as unknown,writes:0,closes:0,upgrades:0,afterCommit:null as null|(()=>void),beforeOpen:null as null|(()=>void)};
  function database(){return {onversionchange:null,close:()=>{state.closes++;},objectStoreNames:{get length(){return state.exists?1:0;},contains:(name:string)=>state.exists&&name==="device-key-kek"},createObjectStore:(name:string)=>{expect(name).toBe("device-key-kek");state.exists=true;},transaction:(name:string,mode:string,options:unknown)=>{
    expect(name).toBe("device-key-kek");expect(options).toEqual({durability:"strict"});
    const tx:{oncomplete:null|(()=>void);onabort:null|(()=>void);onerror:null|(()=>void);abort:()=>void;objectStore:()=>unknown}={oncomplete:null,onabort:null,onerror:null,abort:()=>{aborted=true;queueMicrotask(()=>tx.onabort?.());},objectStore:()=>({get:(key:string)=>{expect(key).toBe("original-device-kek");const request={result:undefined as unknown,onsuccess:null as null|(()=>void)};queueMicrotask(()=>{if(aborted)return;request.result=state.value===undefined?undefined:structuredClone(state.value);request.onsuccess?.();queueMicrotask(()=>{if(aborted)return;if(mode==="readwrite")state.afterCommit?.();tx.oncomplete?.();});});return request;},add:(value:unknown,key:string)=>{expect(mode).toBe("readwrite");expect(key).toBe("original-device-kek");if(state.value!==undefined){tx.abort();return;}state.value=structuredClone(value);state.writes++;}})};let aborted=false;return tx;
  }};}
  const open=vi.fn((name:string,version:number)=>{expect(name).toMatch(/^mdbase\.app\.device-key-kek\.v1\.[0-9a-f]{32}(\.[0-9a-f]{32}){3}$/);expect(version).toBe(1);const result=database(),request={result,transaction:{abort:()=>{aborted=true;state.exists=false;}},onupgradeneeded:null as null|(()=>void),onsuccess:null as null|(()=>void),onerror:null as null|(()=>void),onblocked:null as null|(()=>void)};let aborted=false;queueMicrotask(()=>{state.beforeOpen?.();if(!state.exists){state.upgrades++;request.onupgradeneeded?.();}aborted?request.onerror?.():request.onsuccess?.();});return request;});
  vi.stubGlobal("indexedDB",{open});
  const source={accountId:"11111111-1111-1111-1111-111111111111",connectorId:"66666666-6666-6666-6666-666666666666",deviceId:"44444444-4444-4444-4444-444444444444",installationId:"88888888-8888-8888-8888-888888888888",isCurrent:()=>true,installationOwned:()=>true};
  const options={source,origin,mode:"fresh" as "fresh"|"existing",signal:new AbortController().signal};return{state,open,source,options,sample};
}
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();});
describe("first-party original-device browser KEK provider (actual WebCrypto, stand-in IDB)",()=>{
  it("persists only nonextractable AES256 handle, existing lookup decrypts same ciphertext, single loan",async()=>{
    const f=await fixture(),fresh=await AppIndexedDbDeviceKeyProvider.open(f.options),a=fresh.deviceCustodyKek({signal:f.options.signal});expect(a.extractable).toBe(false);await expect(crypto.subtle.exportKey("raw",a)).rejects.toThrow();
    const iv=new Uint8Array(12),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},a,new Uint8Array([7,8]));expect(()=>fresh.deviceCustodyKek({signal:f.options.signal})).toThrow("preserve storage");fresh.close();
    const warm=await AppIndexedDbDeviceKeyProvider.open({...f.options,mode:"existing"}),b=warm.deviceCustodyKek({signal:f.options.signal});expect(Array.from(new Uint8Array(await crypto.subtle.decrypt({name:"AES-GCM",iv},b,cipher)))).toEqual([7,8]);expect(f.state.writes).toBe(1);expect(Object.keys(f.state.value as object).sort()).toEqual(["key","version"]);warm.close();
  });
  it.each(["accountId","connectorId","deviceId","installationId"] as const)("nil %s refuses before IO",async field=>{const f=await fixture();f.source[field]="00000000-0000-0000-0000-000000000000";await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");expect(f.open).not.toHaveBeenCalled();});
  it.each(["https://foreign.test","https://user:secret@app.example.test","https://app.example.test/path","http://app.example.test"])("foreign/unapproved %s refuses before IO",async value=>{const f=await fixture();await expect(AppIndexedDbDeviceKeyProvider.open({...f.options,origin:value,allowLoopbackHttp:true})).rejects.toThrow("preserve storage");expect(f.open).not.toHaveBeenCalled();});
  it("aborted/non-owned scope and unavailable platform refuse before IO",async()=>{const f=await fixture(),controller=new AbortController();controller.abort();await expect(AppIndexedDbDeviceKeyProvider.open({...f.options,signal:controller.signal})).rejects.toThrow("preserve storage");f.source.installationOwned=()=>false;await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");f.source.installationOwned=()=>true;vi.stubGlobal("CryptoKey",undefined);await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");vi.stubGlobal("CryptoKey",f.sample.constructor);vi.stubGlobal("crypto",undefined);await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");expect(f.open).not.toHaveBeenCalled();});
  it("missing/empty/corrupt existing never creates a substitute key",async()=>{const f=await fixture();await expect(AppIndexedDbDeviceKeyProvider.open({...f.options,mode:"existing"})).rejects.toThrow("preserve storage");expect(f.state.exists).toBe(false);f.state.exists=true;await expect(AppIndexedDbDeviceKeyProvider.open({...f.options,mode:"existing"})).rejects.toThrow("preserve storage");f.state.value={version:1,key:{extractable:false}};await expect(AppIndexedDbDeviceKeyProvider.open({...f.options,mode:"existing"})).rejects.toThrow("preserve storage");expect(f.state.writes).toBe(0);});
  it("an existing committed empty KEK store is recovery-required even if caller requests fresh",async()=>{const f=await fixture();f.state.exists=true;await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");expect(f.state.writes).toBe(0);expect(f.state.value).toBeUndefined();});
  it("fresh-existing conflict and invalid stored key preserve the exact record",async()=>{const f=await fixture();f.state.exists=true;f.state.value={version:1,key:f.sample};await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");expect(f.state.writes).toBe(0);const bad=await crypto.subtle.generateKey({name:"AES-GCM",length:256},true,["encrypt","decrypt"]);f.state.value={version:1,key:bad};await expect(AppIndexedDbDeviceKeyProvider.open({...f.options,mode:"existing"})).rejects.toThrow("preserve storage");expect((f.state.value as {key:CryptoKey}).key.extractable).toBe(true);expect(f.state.writes).toBe(0);});
  it("wrong algorithm/usages/extra record fields never admit an existing handle",async()=>{const f=await fixture();f.state.exists=true;for(const bad of [await crypto.subtle.generateKey({name:"AES-GCM",length:128},false,["encrypt","decrypt"]),await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt"])]){f.state.value={version:1,key:bad};await expect(AppIndexedDbDeviceKeyProvider.open({...f.options,mode:"existing"})).rejects.toThrow("preserve storage");}f.state.value={version:1,key:f.sample,extra:true};await expect(AppIndexedDbDeviceKeyProvider.open({...f.options,mode:"existing"})).rejects.toThrow("preserve storage");expect(f.state.writes).toBe(0);});
  it("ownership lost during real key generation cannot persist a key or regenerate the committed empty store",async()=>{const f=await fixture(),generate=crypto.subtle.generateKey.bind(crypto.subtle);vi.spyOn(crypto.subtle,"generateKey").mockImplementation(async()=>{const next=await generate({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);f.source.installationOwned=()=>false;return next;});await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");expect(f.state.writes).toBe(0);f.source.installationOwned=()=>true;await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");expect(f.state.writes).toBe(0);});
  it("freezes mode/origin/signal before upgrade, later source/callback/lifetime changes fence loan",async()=>{const f=await fixture();f.state.beforeOpen=()=>{f.options.mode="existing";f.options.origin="https://foreign.test";f.options.signal=new AbortController().signal;};const provider=await AppIndexedDbDeviceKeyProvider.open(f.options);expect(f.state.writes).toBe(1);f.source.isCurrent=()=>true;expect(()=>provider.deviceCustodyKek({signal:f.options.signal})).toThrow("preserve storage");provider.close();
    const g=await fixture(),c=new AbortController();const other=await AppIndexedDbDeviceKeyProvider.open({...g.options,signal:c.signal});c.abort();expect(()=>other.deviceCustodyKek({signal:new AbortController().signal})).toThrow("preserve storage");other.close();
  });
  it("source loss during delayed open aborts upgrade; an applied but lost reply is preserved",async()=>{const f=await fixture();f.state.beforeOpen=()=>{f.source.installationOwned=()=>false;};await expect(AppIndexedDbDeviceKeyProvider.open(f.options)).rejects.toThrow("preserve storage");expect(f.state.exists).toBe(false);expect(f.state.writes).toBe(0);
    const g=await fixture();g.state.afterCommit=()=>{g.source.isCurrent=()=>false;};await expect(AppIndexedDbDeviceKeyProvider.open(g.options)).rejects.toThrow("preserve storage");expect(g.state.writes).toBe(1);expect((g.state.value as {key:CryptoKey}).key.extractable).toBe(false);
  });
  it("two create attempts cannot replace the winner",async()=>{const f=await fixture();const outcomes=await Promise.allSettled([AppIndexedDbDeviceKeyProvider.open(f.options),AppIndexedDbDeviceKeyProvider.open(f.options)]);expect(outcomes.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(f.state.writes).toBe(1);for(const r of outcomes)if(r.status==="fulfilled")r.value.close();});
});
