// Builds the e2e plugin: worker bundle (IIFE string) + sqlite3.wasm (base64 gzip)
// -> src/generated.ts -> main.js. Output stays in this directory (never /tmp).
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "../..");
const w = await build({
  entryPoints: [join(here, "src/worker.ts")], bundle: true, write: false, format: "iife", platform: "browser",
  target: "es2022", minify: true, define: { "import.meta.url": '"https://mdbase.invalid/worker.js"' }, logLevel: "warning",
});
const wasm = readFileSync(join(pkg, "node_modules/@sqlite.org/sqlite-wasm/dist/sqlite3.wasm"));
writeFileSync(join(here, "src/generated.ts"),
  `// generated by build.mjs\nexport const WORKER_CODE = ${JSON.stringify(w.outputFiles[0].text)};\n` +
  `export const SQLITE_WASM = { b64: ${JSON.stringify(gzipSync(wasm, { level: 9 }).toString("base64"))}, gzip: true, rawLength: ${wasm.length} } as const;\n`);
await build({
  entryPoints: [join(here, "src/main.ts")], bundle: true, outfile: join(here, "main.js"), format: "cjs", platform: "browser",
  target: "es2020", external: ["obsidian", "electron", "@codemirror/*", "@lezer/*"], logLevel: "warning",
});
const main = readFileSync(join(here, "main.js"));
console.log(JSON.stringify({ mainJs: main.length, mainJsGz: gzipSync(main).length, workerJs: w.outputFiles[0].text.length, sqliteWasm: wasm.length }));
