FROM nats:2.15.0-alpine

COPY deploy/nats/nats.conf /etc/nats/mdbase-connect.conf
COPY deploy/nats/start-nats.sh /usr/local/bin/start-mdbase-connect-nats

EXPOSE 4222 10000
ENTRYPOINT ["/bin/sh", "/usr/local/bin/start-mdbase-connect-nats"]
