// Generated by scripts/generate-application-capabilities.mjs. Do not edit directly.

pub const APPLICATION_CAPABILITY_CONTRACT_VERSION: u32 = 2;

pub const APPLICATION_CAPABILITY_IDS: &[&str] = &[
    "collection.read",
    "records.create",
    "records.edit",
    "records.delete",
    "views.manage",
    "definitions.manage",
    "background.schedule",
    "offline.replica",
];

pub const APPLICATION_SETUP_OPERATIONS: &[&str] =
    &["assess_collection_setup", "apply_collection_setup"];

pub fn application_capability_operations(capability: &str) -> Option<&'static [&'static str]> {
    match capability {
        "collection.read" => Some(&[
            "describe",
            "changes",
            "read",
            "query",
            "list_views",
            "execute_view",
            "read_view_source",
            "validate",
            "read_type",
        ]),
        "records.create" => Some(&["create"]),
        "records.edit" => Some(&["update", "rename"]),
        "records.delete" => Some(&["delete"]),
        "views.manage" => Some(&[
            "create_view_source",
            "update_view_source",
            "delete_view_source",
        ]),
        "definitions.manage" => Some(&[
            "create_type",
            "update_type",
            "assess_type_pack",
            "apply_type_pack",
        ]),
        "background.schedule" => Some(&[
            "list_timers",
            "put_timer",
            "cancel_timer",
            "reconcile_timers",
        ]),
        "offline.replica" => Some(&["sync"]),
        _ => None,
    }
}
