// Generated by scripts/generate-change-events.mjs. Do not edit directly.

use super::*;

pub fn collection_change_kind(event_type: &str) -> Option<&'static str> {
    match event_type {
        "mdbase.record.created" => Some("record.created"),
        "mdbase.record.modified" => Some("record.updated"),
        "mdbase.record.deleted" => Some("record.deleted"),
        "mdbase.record.renamed" => Some("record.renamed"),
        "mdbase.type.changed" => Some("schema.changed"),
        "mdbase.config.changed" => Some("config.changed"),
        "mdbase.contract.changed" => Some("contract.changed"),
        "mdbase.view.changed" => Some("view.changed"),
        "mdbase.view_source.changed" => Some("view.changed"),
        "mdbase.resource.changed" => Some("file.changed"),
        "mdbase.file.put" => Some("file.put"),
        "mdbase.file.remove" => Some("file.removed"),
        "file_put" => Some("file.put"),
        "file_remove" => Some("file.removed"),
        "mdbase.collection.invalidated" => Some("gap"),
        _ => None,
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecordChangePayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_revision: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_types: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub types: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub changed_fields: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body_changed: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub before: Option<serde_json::Map<String, Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub after: Option<serde_json::Map<String, Value>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ResourceChangePayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_revision: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FileChangePayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file: Option<CollectionFileDescriptor>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
}
