// Generated by scripts/generate-operation-catalog.mjs. Do not edit directly.

use serde_json::Value;

pub const OPERATION_CATALOG_VERSION: u32 = 1;

pub const COLLECTION_OPERATIONS: &[&str] = &[
    "describe",
    "changes",
    "read",
    "query",
    "list_views",
    "execute_view",
    "read_view_source",
    "create_view_source",
    "update_view_source",
    "delete_view_source",
    "validate",
    "create",
    "update",
    "delete",
    "rename",
    "read_type",
    "create_type",
    "update_type",
    "assess_type_pack",
    "apply_type_pack",
    "list_timers",
    "put_timer",
    "cancel_timer",
    "reconcile_timers",
    "sync",
];

pub const FILE_CONTROL_MESSAGE_TYPES: &[&str] = &[
    "list_files",
    "open_file_upload",
    "open_file_download",
    "move_file",
    "delete_file",
    "get_file_transfer_status",
    "commit_file_upload",
    "abort_file_transfer",
];

pub const MUTATING_OPERATION_IDENTIFIERS: &[&str] = &[
    "create_view_source",
    "update_view_source",
    "delete_view_source",
    "create",
    "update",
    "delete",
    "rename",
    "create_type",
    "update_type",
    "apply_type_pack",
    "put_timer",
    "cancel_timer",
    "reconcile_timers",
    "sync:mutate",
    "file_control:open_file_upload",
    "file_control:move_file",
    "file_control:delete_file",
    "file_control:commit_file_upload",
    "file_control:abort_file_transfer",
];

pub fn is_collection_operation(operation: &str) -> bool {
    COLLECTION_OPERATIONS.contains(&operation)
}

pub fn operation_input_schema_version(operation: &str, input: &Value) -> Option<u32> {
    if operation == "file_control" {
        return match input.get("type").and_then(Value::as_str).unwrap_or("") {
            "list_files" => Some(1),
            "open_file_upload" => Some(1),
            "open_file_download" => Some(1),
            "move_file" => Some(1),
            "delete_file" => Some(1),
            "get_file_transfer_status" => Some(1),
            "commit_file_upload" => Some(1),
            "abort_file_transfer" => Some(1),
            _ => None,
        };
    }
    match operation {
        "describe" => Some(1),
        "changes" => Some(1),
        "read" => Some(1),
        "query" => Some(1),
        "list_views" => Some(1),
        "execute_view" => Some(1),
        "read_view_source" => Some(1),
        "create_view_source" => Some(1),
        "update_view_source" => Some(1),
        "delete_view_source" => Some(1),
        "validate" => Some(1),
        "create" => Some(1),
        "update" => Some(1),
        "delete" => Some(1),
        "rename" => Some(1),
        "read_type" => Some(1),
        "create_type" => Some(1),
        "update_type" => Some(1),
        "assess_type_pack" => Some(1),
        "apply_type_pack" => Some(1),
        "list_timers" => Some(1),
        "put_timer" => Some(1),
        "cancel_timer" => Some(1),
        "reconcile_timers" => Some(1),
        "sync" => Some(1),
        _ => None,
    }
}

pub fn mutation_operation_identifier<'a>(operation: &'a str, input: &Value) -> Option<&'a str> {
    if input.get("dry_run").and_then(Value::as_bool) == Some(true) {
        return None;
    }
    if operation == "file_control" {
        return match input.get("type").and_then(Value::as_str).unwrap_or("") {
            "open_file_upload" => Some("file_control:open_file_upload"),
            "move_file" => Some("file_control:move_file"),
            "delete_file" => Some("file_control:delete_file"),
            "commit_file_upload" => Some("file_control:commit_file_upload"),
            "abort_file_transfer" => Some("file_control:abort_file_transfer"),
            _ => None,
        };
    }
    match operation {
        "create_view_source" => Some("create_view_source"),
        "update_view_source" => Some("update_view_source"),
        "delete_view_source" => Some("delete_view_source"),
        "create" => Some("create"),
        "update" => Some("update"),
        "delete" => Some("delete"),
        "rename" => Some("rename"),
        "create_type" => Some("create_type"),
        "update_type" => Some("update_type"),
        "apply_type_pack" => Some("apply_type_pack"),
        "put_timer" => Some("put_timer"),
        "cancel_timer" => Some("cancel_timer"),
        "reconcile_timers" => Some("reconcile_timers"),
        "sync" if input.get("action").and_then(Value::as_str) == Some("mutate") => {
            Some("sync:mutate")
        }
        _ => None,
    }
}

pub fn is_mutating_operation(operation: &str, input: &Value) -> bool {
    mutation_operation_identifier(operation, input).is_some()
}
