// Generated by scripts/generate-connect-problems.mjs. Do not edit directly.

use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const CONNECT_PROBLEM_VERSION: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConnectProblemCategory {
    Authorization,
    Availability,
    Cancellation,
    Compatibility,
    Conflict,
    Integrity,
    Internal,
    Selection,
    Validation,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConnectRecoveryAction {
    ChooseCollection,
    ContactSupport,
    FixRequest,
    None,
    Reauthorize,
    Refresh,
    RepairCollection,
    ResumeConnectorAccess,
    ResolveConflict,
    ResolveOutcome,
    Retry,
    UpgradeApplication,
    UpgradeCollection,
    UpgradeConnector,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConnectOperationOutcome {
    NotSent,
    Rejected,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConnectProblemDefinition {
    pub category: ConnectProblemCategory,
    pub recovery: ConnectRecoveryAction,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ConnectProblem {
    pub problem_version: u32,
    pub code: String,
    pub category: ConnectProblemCategory,
    pub recovery: ConnectRecoveryAction,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operation_outcome: Option<ConnectOperationOutcome>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub server_code: Option<String>,
}

#[rustfmt::skip]
pub fn connect_problem_definition(code: &str) -> Option<ConnectProblemDefinition> {
    match code {
        "access_denied" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "access_paused" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::ResumeConnectorAccess }),
        "approval_window_blocked" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "authority_authorization_changed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "authorization_cancelled" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Cancellation, recovery: ConnectRecoveryAction::None }),
        "authorization_expired" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "browser_required" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::None }),
        "callback_url_required" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "change_cursor_reset" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "collection_access_denied" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "collection_configuration_invalid" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::RepairCollection }),
        "collection_contracts_missing" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::ChooseCollection }),
        "collection_incompatible" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::ChooseCollection }),
        "collection_invalid" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::RepairCollection }),
        "collection_kind_unsupported" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::ChooseCollection }),
        "collection_mismatch" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Selection, recovery: ConnectRecoveryAction::ChooseCollection }),
        "collection_not_found" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Selection, recovery: ConnectRecoveryAction::ChooseCollection }),
        "collection_not_ready" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Selection, recovery: ConnectRecoveryAction::ChooseCollection }),
        "collection_not_selected" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Selection, recovery: ConnectRecoveryAction::ChooseCollection }),
        "collection_type_registry_invalid" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::RepairCollection }),
        "collection_version_unsupported" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::UpgradeCollection }),
        "concurrent_modification" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "connector_identity_changed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Integrity, recovery: ConnectRecoveryAction::Reauthorize }),
        "connector_offline" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "connector_upgrade_required" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::UpgradeConnector }),
        "device_authorization_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "direct_operation_rejected" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "discovery_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "encrypted_relay_rejected" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "encryption_required" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "expired_token" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "file_changed_during_move" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "file_changed_during_read" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "file_move_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Internal, recovery: ConnectRecoveryAction::ContactSupport }),
        "file_mutation_conflict" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::ResolveConflict }),
        "file_not_found" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "file_source_mismatch" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "file_upload_incomplete" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Retry }),
        "hosted_provider_unavailable" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "insufficient_access" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "invalid_application_manifest" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "invalid_callback" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "invalid_device_authorization_response" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Integrity, recovery: ConnectRecoveryAction::ContactSupport }),
        "invalid_encrypted_response" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Integrity, recovery: ConnectRecoveryAction::ContactSupport }),
        "invalid_loopback_url" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "invalid_mutation_id" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "invalid_operation_response" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Integrity, recovery: ConnectRecoveryAction::ContactSupport }),
        "invalid_path" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "invalid_preflight" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "invalid_push_payload" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "invalid_push_subscription" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "invalid_request" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "invalid_token_response" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Integrity, recovery: ConnectRecoveryAction::ContactSupport }),
        "managed_fcm_not_declared" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::FixRequest }),
        "manifest_load_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "manifest_required" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "missing_grant_key" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "no_pending_mutation" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "not_authorized" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "not_remote_authority" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::ChooseCollection }),
        "notification_criterion_not_declared" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "notification_reauthorization_required" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "notification_registration_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "notification_unregistration_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "notifications_not_declared" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::FixRequest }),
        "notifications_unavailable" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "operation_cancelled" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Cancellation, recovery: ConnectRecoveryAction::None }),
        "operation_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Internal, recovery: ConnectRecoveryAction::ContactSupport }),
        "operation_invalid" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "operation_outcome_unknown" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::ResolveOutcome }),
        "path_occupied" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::ResolveConflict }),
        "pending_mutation_unresolved" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::ResolveOutcome }),
        "query_snapshot_changed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "rate_limited" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "redirect_uri_required" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "reference_updates_unsupported" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::FixRequest }),
        "relay_authorization_expired" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "relay_unavailable" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "sandbox_unsupported" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::FixRequest }),
        "scope_denied" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Authorization, recovery: ConnectRecoveryAction::Reauthorize }),
        "stale_file_revision" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Conflict, recovery: ConnectRecoveryAction::Refresh }),
        "storage_required" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::None }),
        "sync_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "temporarily_unavailable" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "timeout" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "token_exchange_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Availability, recovery: ConnectRecoveryAction::Retry }),
        "type_pack_provision_failed" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::RepairCollection }),
        "unknown_collection" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Selection, recovery: ConnectRecoveryAction::ChooseCollection }),
        "unsafe_file_path" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Validation, recovery: ConnectRecoveryAction::FixRequest }),
        "unsupported_encryption" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::UpgradeApplication }),
        "unsupported_operation" => Some(ConnectProblemDefinition { category: ConnectProblemCategory::Compatibility, recovery: ConnectRecoveryAction::FixRequest }),
        _ => None,
    }
}

impl ConnectProblem {
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self {
        let server_code = code.into();
        let message = message.into();
        match connect_problem_definition(&server_code) {
            Some(definition) => Self {
                problem_version: CONNECT_PROBLEM_VERSION,
                code: server_code,
                category: definition.category,
                recovery: definition.recovery,
                message,
                details: None,
                operation_outcome: None,
                trace_id: None,
                server_code: None,
            },
            None => Self {
                problem_version: CONNECT_PROBLEM_VERSION,
                code: "unknown".to_string(),
                category: ConnectProblemCategory::Unknown,
                recovery: ConnectRecoveryAction::None,
                message,
                details: None,
                operation_outcome: None,
                trace_id: None,
                server_code: Some(server_code),
            },
        }
    }

    pub fn with_details(mut self, details: Value) -> Self {
        self.details = Some(details);
        self
    }

    pub fn with_operation_outcome(mut self, outcome: ConnectOperationOutcome) -> Self {
        self.operation_outcome = Some(outcome);
        self
    }

    pub fn with_trace_id(mut self, trace_id: impl Into<String>) -> Self {
        self.trace_id = Some(trace_id.into());
        self
    }
}
