// Generated by scripts/generate-application-capabilities.mjs. Do not edit directly.

import type { CollectionOperation } from "./operations.js";

export const APPLICATION_CAPABILITY_CONTRACT_VERSION = 2 as const;

export const APPLICATION_CAPABILITY_DEFINITIONS = {
  "collection.read": ["describe","changes","read","query","list_views","execute_view","read_view_source","validate","read_type"],
  "records.create": ["create"],
  "records.edit": ["update","rename"],
  "records.delete": ["delete"],
  "views.manage": ["create_view_source","update_view_source","delete_view_source"],
  "definitions.manage": ["create_type","update_type","assess_type_pack","apply_type_pack"],
  "background.schedule": ["list_timers","put_timer","cancel_timer","reconcile_timers"],
  "offline.replica": ["sync"]
} as const satisfies Record<string, readonly CollectionOperation[]>;

export const APPLICATION_SETUP_OPERATIONS = [
  "assess_collection_setup",
  "apply_collection_setup"
] as const satisfies readonly CollectionOperation[];

export type ApplicationCapabilityId = keyof typeof APPLICATION_CAPABILITY_DEFINITIONS;

export interface ApplicationCapabilityRequirements {
  contract_version: typeof APPLICATION_CAPABILITY_CONTRACT_VERSION;
  required: ApplicationCapabilityId[];
  optional?: ApplicationCapabilityId[];
}

export function operationsForApplicationCapabilities(
  requirements: ApplicationCapabilityRequirements,
  options: { includeOptional?: boolean } = {}
): CollectionOperation[] {
  const capabilities = options.includeOptional === false
    ? requirements.required
    : [...requirements.required, ...(requirements.optional ?? [])];
  return [...new Set(capabilities.flatMap(
    (capability) => APPLICATION_CAPABILITY_DEFINITIONS[capability]
  ))];
}

export function capabilityOperations(
  capability: ApplicationCapabilityId
): CollectionOperation[] {
  return [...APPLICATION_CAPABILITY_DEFINITIONS[capability]];
}

export function applicationOperationSelectionIsAtomic(
  requirements: ApplicationCapabilityRequirements,
  operations: readonly string[]
): boolean {
  const selected = new Set(operations);
  const declared = [...requirements.required, ...(requirements.optional ?? [])];
  const allowed = new Set<string>(declared.flatMap(
    (capability) => APPLICATION_CAPABILITY_DEFINITIONS[capability]
  ));
  if ([...selected].some((operation) => !allowed.has(operation))) {
    return false;
  }
  return declared.every((capability) => {
    const capabilityOperations = APPLICATION_CAPABILITY_DEFINITIONS[capability];
    const count = capabilityOperations.filter((operation) => selected.has(operation)).length;
    return requirements.required.includes(capability)
      ? count === capabilityOperations.length
      : count === 0 || count === capabilityOperations.length;
  });
}
