// Generated by scripts/generate-change-events.mjs. Do not edit directly.

import type { CollectionFileDescriptor } from "./files.js";

export const CHANGE_EVENT_KINDS = {
  "mdbase.record.created": "record.created",
  "mdbase.record.modified": "record.updated",
  "mdbase.record.deleted": "record.deleted",
  "mdbase.record.renamed": "record.renamed",
  "mdbase.type.changed": "schema.changed",
  "mdbase.config.changed": "config.changed",
  "mdbase.contract.changed": "contract.changed",
  "mdbase.view.changed": "view.changed",
  "mdbase.view_source.changed": "view.changed",
  "mdbase.resource.changed": "file.changed",
  "mdbase.file.put": "file.put",
  "mdbase.file.remove": "file.removed",
  "file_put": "file.put",
  "file_remove": "file.removed",
  "mdbase.collection.invalidated": "gap"
} as const;

export type KnownCollectionChangeType = keyof typeof CHANGE_EVENT_KINDS;

/** Optional metadata: older authorities may omit fields; null means unavailable. */
export interface RecordChangePayload {
  path?: string | null;
  from?: string | null;
  to?: string | null;
  previous_revision?: string | null;
  revision?: string | null;
  previous_types?: string[] | null;
  types?: string[] | null;
  changed_fields?: string[] | null;
  body_changed?: boolean | null;
  before?: Record<string, unknown> | null;
  after?: Record<string, unknown> | null;
}

/** Optional metadata: older authorities may omit fields; null means unavailable. */
export interface ResourceChangePayload {
  name?: string | null;
  path?: string | null;
  previous_revision?: string | null;
  revision?: string | null;
  reason?: string | null;
}

/** Optional metadata: older authorities may omit fields; null means unavailable. */
export interface FileChangePayload {
  file?: CollectionFileDescriptor | null;
  file_id?: string | null;
  previous_path?: string | null;
  revision?: string | null;
}
