// Generated by scripts/generate-connect-problems.mjs. Do not edit directly.

export const CONNECT_PROBLEM_VERSION = 1 as const;

export const CONNECT_PROBLEM_CATALOG = {
  "access_denied": { category: "authorization", recovery: "reauthorize" },
  "access_paused": { category: "availability", recovery: "resume_connector_access" },
  "application_identity_unavailable": { category: "compatibility", recovery: "upgrade_application" },
  "approval_window_blocked": { category: "authorization", recovery: "reauthorize" },
  "authority_authorization_changed": { category: "authorization", recovery: "reauthorize" },
  "authorization_binding_incompatible": { category: "compatibility", recovery: "upgrade_application" },
  "authorization_cancelled": { category: "cancellation", recovery: "none" },
  "authorization_expired": { category: "authorization", recovery: "reauthorize" },
  "authorization_replayed": { category: "integrity", recovery: "reauthorize" },
  "browser_required": { category: "compatibility", recovery: "none" },
  "callback_url_required": { category: "validation", recovery: "fix_request" },
  "capability_contract_incompatible": { category: "compatibility", recovery: "upgrade_application" },
  "change_cursor_reset": { category: "conflict", recovery: "refresh" },
  "collection_access_denied": { category: "authorization", recovery: "reauthorize" },
  "collection_configuration_invalid": { category: "validation", recovery: "repair_collection" },
  "collection_contracts_missing": { category: "compatibility", recovery: "choose_collection" },
  "collection_incompatible": { category: "compatibility", recovery: "choose_collection" },
  "collection_invalid": { category: "validation", recovery: "repair_collection" },
  "collection_kind_unsupported": { category: "compatibility", recovery: "choose_collection" },
  "collection_mismatch": { category: "selection", recovery: "choose_collection" },
  "collection_not_found": { category: "selection", recovery: "choose_collection" },
  "collection_not_ready": { category: "selection", recovery: "choose_collection" },
  "collection_not_selected": { category: "selection", recovery: "choose_collection" },
  "collection_type_registry_invalid": { category: "validation", recovery: "repair_collection" },
  "collection_version_unsupported": { category: "compatibility", recovery: "upgrade_collection" },
  "concurrent_modification": { category: "conflict", recovery: "refresh" },
  "connector_busy": { category: "availability", recovery: "retry" },
  "connector_identity_changed": { category: "integrity", recovery: "reauthorize" },
  "connector_offline": { category: "availability", recovery: "retry" },
  "connector_upgrade_required": { category: "compatibility", recovery: "upgrade_connector" },
  "device_authorization_failed": { category: "authorization", recovery: "reauthorize" },
  "direct_operation_rejected": { category: "authorization", recovery: "reauthorize" },
  "discovery_failed": { category: "availability", recovery: "retry" },
  "durable_mutation_unsupported": { category: "compatibility", recovery: "upgrade_connector" },
  "encrypted_relay_rejected": { category: "authorization", recovery: "reauthorize" },
  "encryption_required": { category: "authorization", recovery: "reauthorize" },
  "expired_token": { category: "authorization", recovery: "reauthorize" },
  "file_changed_during_move": { category: "conflict", recovery: "refresh" },
  "file_changed_during_read": { category: "conflict", recovery: "refresh" },
  "file_index_warming": { category: "availability", recovery: "retry" },
  "file_move_failed": { category: "internal", recovery: "contact_support" },
  "file_mutation_conflict": { category: "conflict", recovery: "resolve_conflict" },
  "file_not_found": { category: "conflict", recovery: "refresh" },
  "file_source_mismatch": { category: "conflict", recovery: "refresh" },
  "file_upload_incomplete": { category: "conflict", recovery: "retry" },
  "fresh_request_required": { category: "availability", recovery: "retry" },
  "hosted_provider_unavailable": { category: "availability", recovery: "retry" },
  "insufficient_access": { category: "authorization", recovery: "reauthorize" },
  "invalid_application_authorization": { category: "validation", recovery: "fix_request" },
  "invalid_application_manifest": { category: "validation", recovery: "fix_request" },
  "invalid_callback": { category: "validation", recovery: "fix_request" },
  "invalid_device_authorization_response": { category: "integrity", recovery: "contact_support" },
  "invalid_encrypted_response": { category: "integrity", recovery: "contact_support" },
  "invalid_loopback_url": { category: "validation", recovery: "fix_request" },
  "invalid_mutation_id": { category: "validation", recovery: "fix_request" },
  "invalid_operation_response": { category: "integrity", recovery: "contact_support" },
  "invalid_path": { category: "validation", recovery: "fix_request" },
  "invalid_preflight": { category: "conflict", recovery: "refresh" },
  "invalid_push_payload": { category: "validation", recovery: "fix_request" },
  "invalid_push_subscription": { category: "validation", recovery: "fix_request" },
  "invalid_request": { category: "validation", recovery: "fix_request" },
  "invalid_token_response": { category: "integrity", recovery: "contact_support" },
  "managed_fcm_not_declared": { category: "compatibility", recovery: "fix_request" },
  "manifest_load_failed": { category: "availability", recovery: "retry" },
  "manifest_required": { category: "validation", recovery: "fix_request" },
  "missing_grant_key": { category: "authorization", recovery: "reauthorize" },
  "mutation_recovery_expired": { category: "compatibility", recovery: "none" },
  "mutation_request_conflict": { category: "conflict", recovery: "resolve_conflict" },
  "no_pending_mutation": { category: "conflict", recovery: "refresh" },
  "not_authorized": { category: "authorization", recovery: "reauthorize" },
  "not_remote_authority": { category: "compatibility", recovery: "choose_collection" },
  "notification_criterion_not_declared": { category: "validation", recovery: "fix_request" },
  "notification_reauthorization_required": { category: "authorization", recovery: "reauthorize" },
  "notification_registration_failed": { category: "availability", recovery: "retry" },
  "notification_unregistration_failed": { category: "availability", recovery: "retry" },
  "notifications_not_declared": { category: "compatibility", recovery: "fix_request" },
  "notifications_unavailable": { category: "availability", recovery: "retry" },
  "operation_cancelled": { category: "cancellation", recovery: "none" },
  "operation_failed": { category: "internal", recovery: "contact_support" },
  "operation_invalid": { category: "validation", recovery: "fix_request" },
  "operation_outcome_unknown": { category: "conflict", recovery: "resolve_outcome" },
  "path_occupied": { category: "conflict", recovery: "resolve_conflict" },
  "pending_mutation_unresolved": { category: "conflict", recovery: "resolve_outcome" },
  "query_snapshot_changed": { category: "conflict", recovery: "refresh" },
  "rate_limited": { category: "availability", recovery: "retry" },
  "reconnect_required": { category: "authorization", recovery: "reauthorize" },
  "redirect_uri_required": { category: "validation", recovery: "fix_request" },
  "reference_updates_unsupported": { category: "compatibility", recovery: "fix_request" },
  "registry_backup_invalid": { category: "integrity", recovery: "contact_support" },
  "registry_busy": { category: "availability", recovery: "retry" },
  "registry_corrupt": { category: "integrity", recovery: "repair_collection" },
  "registry_migration_failed": { category: "internal", recovery: "contact_support" },
  "registry_schema_incompatible": { category: "compatibility", recovery: "upgrade_connector" },
  "relay_authorization_expired": { category: "authorization", recovery: "reauthorize" },
  "relay_unavailable": { category: "availability", recovery: "retry" },
  "sandbox_unsupported": { category: "compatibility", recovery: "fix_request" },
  "scope_denied": { category: "authorization", recovery: "reauthorize" },
  "stale_file_revision": { category: "conflict", recovery: "refresh" },
  "storage_required": { category: "compatibility", recovery: "none" },
  "sync_failed": { category: "availability", recovery: "retry" },
  "temporarily_unavailable": { category: "availability", recovery: "retry" },
  "timeout": { category: "availability", recovery: "retry" },
  "token_exchange_failed": { category: "availability", recovery: "retry" },
  "transport_protocol_incompatible": { category: "compatibility", recovery: "upgrade_connector" },
  "type_pack_provision_failed": { category: "validation", recovery: "repair_collection" },
  "unknown_collection": { category: "selection", recovery: "choose_collection" },
  "unsafe_file_path": { category: "validation", recovery: "fix_request" },
  "unsupported_encryption": { category: "compatibility", recovery: "upgrade_application" },
  "unsupported_operation": { category: "compatibility", recovery: "fix_request" }
} as const;

export type ConnectProblemCode = keyof typeof CONNECT_PROBLEM_CATALOG;
export type ConnectProblemCategory = "authorization" | "availability" | "cancellation" | "compatibility" | "conflict" | "integrity" | "internal" | "selection" | "validation" | "unknown";
export type ConnectRecoveryAction = "choose_collection" | "contact_support" | "fix_request" | "none" | "reauthorize" | "refresh" | "repair_collection" | "resume_connector_access" | "resolve_conflict" | "resolve_outcome" | "retry" | "upgrade_application" | "upgrade_collection" | "upgrade_connector";
export type ConnectOperationOutcome = "not_sent" | "rejected" | "unknown";

export interface ConnectProblemBase {
  problem_version: typeof CONNECT_PROBLEM_VERSION;
  message: string;
  operation_outcome?: ConnectOperationOutcome;
  trace_id?: string;
}

export interface ConnectProblemDetailsByCode {
  "access_denied": {
  "return_to"?: string;
};
  "access_paused": undefined;
  "application_identity_unavailable": undefined;
  "approval_window_blocked": {
  "user_code": string;
  "verification_uri": string;
  "verification_uri_complete": string;
  "expires_at": number;
  "interval_seconds": number;
};
  "authority_authorization_changed": undefined;
  "authorization_binding_incompatible": {
  "contract": string;
  "required": Array<number>;
  "supported": Array<number>;
  "peer": string;
  "operation"?: string;
};
  "authorization_cancelled": undefined;
  "authorization_expired": undefined;
  "authorization_replayed": undefined;
  "browser_required": undefined;
  "callback_url_required": undefined;
  "capability_contract_incompatible": {
  "contract": string;
  "required": Array<number>;
  "supported": Array<number>;
  "peer": string;
  "operation"?: string;
};
  "change_cursor_reset": undefined;
  "collection_access_denied": undefined;
  "collection_configuration_invalid": {
  "diagnostics": Array<Record<string, unknown>>;
};
  "collection_contracts_missing": {
  "contracts": Array<{
    "id": string;
    "version": string;
  }>;
};
  "collection_incompatible": undefined;
  "collection_invalid": {
  "diagnostics": Array<Record<string, unknown>>;
};
  "collection_kind_unsupported": undefined;
  "collection_mismatch": undefined;
  "collection_not_found": undefined;
  "collection_not_ready": undefined;
  "collection_not_selected": undefined;
  "collection_type_registry_invalid": {
  "diagnostics": Array<Record<string, unknown>>;
};
  "collection_version_unsupported": {
  "current_version": string;
  "required_version": string;
};
  "concurrent_modification": undefined;
  "connector_busy": undefined;
  "connector_identity_changed": undefined;
  "connector_offline": {
  "connector_name"?: string;
};
  "connector_upgrade_required": undefined;
  "device_authorization_failed": undefined;
  "direct_operation_rejected": undefined;
  "discovery_failed": undefined;
  "durable_mutation_unsupported": {
  "contract": string;
  "required": Array<number>;
  "supported": Array<number>;
  "peer": string;
  "operation"?: string;
};
  "encrypted_relay_rejected": undefined;
  "encryption_required": undefined;
  "expired_token": undefined;
  "file_changed_during_move": undefined;
  "file_changed_during_read": undefined;
  "file_index_warming": undefined;
  "file_move_failed": undefined;
  "file_mutation_conflict": undefined;
  "file_not_found": undefined;
  "file_source_mismatch": undefined;
  "file_upload_incomplete": undefined;
  "fresh_request_required": undefined;
  "hosted_provider_unavailable": undefined;
  "insufficient_access": {
  "required_operations": Array<string>;
  "granted_operations": Array<string>;
  "missing_operations": Array<string>;
};
  "invalid_application_authorization": undefined;
  "invalid_application_manifest": {
  "issues": Array<{
    "path": string;
    "keyword": string;
    "message": string;
    "params": Record<string, unknown>;
  }>;
};
  "invalid_callback": undefined;
  "invalid_device_authorization_response": undefined;
  "invalid_encrypted_response": undefined;
  "invalid_loopback_url": undefined;
  "invalid_mutation_id": undefined;
  "invalid_operation_response": undefined;
  "invalid_path": undefined;
  "invalid_preflight": undefined;
  "invalid_push_payload": undefined;
  "invalid_push_subscription": undefined;
  "invalid_request": undefined;
  "invalid_token_response": undefined;
  "managed_fcm_not_declared": undefined;
  "manifest_load_failed": undefined;
  "manifest_required": undefined;
  "missing_grant_key": undefined;
  "mutation_recovery_expired": undefined;
  "mutation_request_conflict": {
  "request_id": string;
};
  "no_pending_mutation": undefined;
  "not_authorized": undefined;
  "not_remote_authority": undefined;
  "notification_criterion_not_declared": undefined;
  "notification_reauthorization_required": undefined;
  "notification_registration_failed": undefined;
  "notification_unregistration_failed": undefined;
  "notifications_not_declared": undefined;
  "notifications_unavailable": undefined;
  "operation_cancelled": undefined;
  "operation_failed": undefined;
  "operation_invalid": {
  "diagnostics": Array<Record<string, unknown>>;
  "partial_result"?: unknown;
};
  "operation_outcome_unknown": {
  "request_id": string;
};
  "path_occupied": undefined;
  "pending_mutation_unresolved": undefined;
  "query_snapshot_changed": undefined;
  "rate_limited": {
  "retry_after_ms"?: number;
};
  "reconnect_required": undefined;
  "redirect_uri_required": undefined;
  "reference_updates_unsupported": undefined;
  "registry_backup_invalid": undefined;
  "registry_busy": undefined;
  "registry_corrupt": undefined;
  "registry_migration_failed": undefined;
  "registry_schema_incompatible": undefined;
  "relay_authorization_expired": undefined;
  "relay_unavailable": undefined;
  "sandbox_unsupported": undefined;
  "scope_denied": undefined;
  "stale_file_revision": undefined;
  "storage_required": undefined;
  "sync_failed": undefined;
  "temporarily_unavailable": undefined;
  "timeout": undefined;
  "token_exchange_failed": undefined;
  "transport_protocol_incompatible": {
  "contract": string;
  "required": Array<number>;
  "supported": Array<number>;
  "peer": string;
  "operation"?: string;
};
  "type_pack_provision_failed": undefined;
  "unknown_collection": undefined;
  "unsafe_file_path": undefined;
  "unsupported_encryption": undefined;
  "unsupported_operation": undefined;
}

export interface ConnectProblemByCode {
  "access_denied": ConnectProblemBase & {
    code: "access_denied";
    category: "authorization";
    recovery: "reauthorize";
    details?: ConnectProblemDetailsByCode["access_denied"];
  };
  "access_paused": ConnectProblemBase & {
    code: "access_paused";
    category: "availability";
    recovery: "resume_connector_access";
    details?: never;
  };
  "application_identity_unavailable": ConnectProblemBase & {
    code: "application_identity_unavailable";
    category: "compatibility";
    recovery: "upgrade_application";
    details?: never;
  };
  "approval_window_blocked": ConnectProblemBase & {
    code: "approval_window_blocked";
    category: "authorization";
    recovery: "reauthorize";
    details: ConnectProblemDetailsByCode["approval_window_blocked"];
  };
  "authority_authorization_changed": ConnectProblemBase & {
    code: "authority_authorization_changed";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "authorization_binding_incompatible": ConnectProblemBase & {
    code: "authorization_binding_incompatible";
    category: "compatibility";
    recovery: "upgrade_application";
    details: ConnectProblemDetailsByCode["authorization_binding_incompatible"];
  };
  "authorization_cancelled": ConnectProblemBase & {
    code: "authorization_cancelled";
    category: "cancellation";
    recovery: "none";
    details?: never;
  };
  "authorization_expired": ConnectProblemBase & {
    code: "authorization_expired";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "authorization_replayed": ConnectProblemBase & {
    code: "authorization_replayed";
    category: "integrity";
    recovery: "reauthorize";
    details?: never;
  };
  "browser_required": ConnectProblemBase & {
    code: "browser_required";
    category: "compatibility";
    recovery: "none";
    details?: never;
  };
  "callback_url_required": ConnectProblemBase & {
    code: "callback_url_required";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "capability_contract_incompatible": ConnectProblemBase & {
    code: "capability_contract_incompatible";
    category: "compatibility";
    recovery: "upgrade_application";
    details: ConnectProblemDetailsByCode["capability_contract_incompatible"];
  };
  "change_cursor_reset": ConnectProblemBase & {
    code: "change_cursor_reset";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "collection_access_denied": ConnectProblemBase & {
    code: "collection_access_denied";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "collection_configuration_invalid": ConnectProblemBase & {
    code: "collection_configuration_invalid";
    category: "validation";
    recovery: "repair_collection";
    details: ConnectProblemDetailsByCode["collection_configuration_invalid"];
  };
  "collection_contracts_missing": ConnectProblemBase & {
    code: "collection_contracts_missing";
    category: "compatibility";
    recovery: "choose_collection";
    details: ConnectProblemDetailsByCode["collection_contracts_missing"];
  };
  "collection_incompatible": ConnectProblemBase & {
    code: "collection_incompatible";
    category: "compatibility";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_invalid": ConnectProblemBase & {
    code: "collection_invalid";
    category: "validation";
    recovery: "repair_collection";
    details: ConnectProblemDetailsByCode["collection_invalid"];
  };
  "collection_kind_unsupported": ConnectProblemBase & {
    code: "collection_kind_unsupported";
    category: "compatibility";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_mismatch": ConnectProblemBase & {
    code: "collection_mismatch";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_not_found": ConnectProblemBase & {
    code: "collection_not_found";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_not_ready": ConnectProblemBase & {
    code: "collection_not_ready";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_not_selected": ConnectProblemBase & {
    code: "collection_not_selected";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_type_registry_invalid": ConnectProblemBase & {
    code: "collection_type_registry_invalid";
    category: "validation";
    recovery: "repair_collection";
    details: ConnectProblemDetailsByCode["collection_type_registry_invalid"];
  };
  "collection_version_unsupported": ConnectProblemBase & {
    code: "collection_version_unsupported";
    category: "compatibility";
    recovery: "upgrade_collection";
    details: ConnectProblemDetailsByCode["collection_version_unsupported"];
  };
  "concurrent_modification": ConnectProblemBase & {
    code: "concurrent_modification";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "connector_busy": ConnectProblemBase & {
    code: "connector_busy";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "connector_identity_changed": ConnectProblemBase & {
    code: "connector_identity_changed";
    category: "integrity";
    recovery: "reauthorize";
    details?: never;
  };
  "connector_offline": ConnectProblemBase & {
    code: "connector_offline";
    category: "availability";
    recovery: "retry";
    details?: ConnectProblemDetailsByCode["connector_offline"];
  };
  "connector_upgrade_required": ConnectProblemBase & {
    code: "connector_upgrade_required";
    category: "compatibility";
    recovery: "upgrade_connector";
    details?: never;
  };
  "device_authorization_failed": ConnectProblemBase & {
    code: "device_authorization_failed";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "direct_operation_rejected": ConnectProblemBase & {
    code: "direct_operation_rejected";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "discovery_failed": ConnectProblemBase & {
    code: "discovery_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "durable_mutation_unsupported": ConnectProblemBase & {
    code: "durable_mutation_unsupported";
    category: "compatibility";
    recovery: "upgrade_connector";
    details: ConnectProblemDetailsByCode["durable_mutation_unsupported"];
  };
  "encrypted_relay_rejected": ConnectProblemBase & {
    code: "encrypted_relay_rejected";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "encryption_required": ConnectProblemBase & {
    code: "encryption_required";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "expired_token": ConnectProblemBase & {
    code: "expired_token";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "file_changed_during_move": ConnectProblemBase & {
    code: "file_changed_during_move";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "file_changed_during_read": ConnectProblemBase & {
    code: "file_changed_during_read";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "file_index_warming": ConnectProblemBase & {
    code: "file_index_warming";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "file_move_failed": ConnectProblemBase & {
    code: "file_move_failed";
    category: "internal";
    recovery: "contact_support";
    details?: never;
  };
  "file_mutation_conflict": ConnectProblemBase & {
    code: "file_mutation_conflict";
    category: "conflict";
    recovery: "resolve_conflict";
    details?: never;
  };
  "file_not_found": ConnectProblemBase & {
    code: "file_not_found";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "file_source_mismatch": ConnectProblemBase & {
    code: "file_source_mismatch";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "file_upload_incomplete": ConnectProblemBase & {
    code: "file_upload_incomplete";
    category: "conflict";
    recovery: "retry";
    details?: never;
  };
  "fresh_request_required": ConnectProblemBase & {
    code: "fresh_request_required";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "hosted_provider_unavailable": ConnectProblemBase & {
    code: "hosted_provider_unavailable";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "insufficient_access": ConnectProblemBase & {
    code: "insufficient_access";
    category: "authorization";
    recovery: "reauthorize";
    details: ConnectProblemDetailsByCode["insufficient_access"];
  };
  "invalid_application_authorization": ConnectProblemBase & {
    code: "invalid_application_authorization";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_application_manifest": ConnectProblemBase & {
    code: "invalid_application_manifest";
    category: "validation";
    recovery: "fix_request";
    details: ConnectProblemDetailsByCode["invalid_application_manifest"];
  };
  "invalid_callback": ConnectProblemBase & {
    code: "invalid_callback";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_device_authorization_response": ConnectProblemBase & {
    code: "invalid_device_authorization_response";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "invalid_encrypted_response": ConnectProblemBase & {
    code: "invalid_encrypted_response";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "invalid_loopback_url": ConnectProblemBase & {
    code: "invalid_loopback_url";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_mutation_id": ConnectProblemBase & {
    code: "invalid_mutation_id";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_operation_response": ConnectProblemBase & {
    code: "invalid_operation_response";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "invalid_path": ConnectProblemBase & {
    code: "invalid_path";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_preflight": ConnectProblemBase & {
    code: "invalid_preflight";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "invalid_push_payload": ConnectProblemBase & {
    code: "invalid_push_payload";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_push_subscription": ConnectProblemBase & {
    code: "invalid_push_subscription";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_request": ConnectProblemBase & {
    code: "invalid_request";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_token_response": ConnectProblemBase & {
    code: "invalid_token_response";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "managed_fcm_not_declared": ConnectProblemBase & {
    code: "managed_fcm_not_declared";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
  "manifest_load_failed": ConnectProblemBase & {
    code: "manifest_load_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "manifest_required": ConnectProblemBase & {
    code: "manifest_required";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "missing_grant_key": ConnectProblemBase & {
    code: "missing_grant_key";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "mutation_recovery_expired": ConnectProblemBase & {
    code: "mutation_recovery_expired";
    category: "compatibility";
    recovery: "none";
    details?: never;
  };
  "mutation_request_conflict": ConnectProblemBase & {
    code: "mutation_request_conflict";
    category: "conflict";
    recovery: "resolve_conflict";
    details: ConnectProblemDetailsByCode["mutation_request_conflict"];
  };
  "no_pending_mutation": ConnectProblemBase & {
    code: "no_pending_mutation";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "not_authorized": ConnectProblemBase & {
    code: "not_authorized";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "not_remote_authority": ConnectProblemBase & {
    code: "not_remote_authority";
    category: "compatibility";
    recovery: "choose_collection";
    details?: never;
  };
  "notification_criterion_not_declared": ConnectProblemBase & {
    code: "notification_criterion_not_declared";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "notification_reauthorization_required": ConnectProblemBase & {
    code: "notification_reauthorization_required";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "notification_registration_failed": ConnectProblemBase & {
    code: "notification_registration_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "notification_unregistration_failed": ConnectProblemBase & {
    code: "notification_unregistration_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "notifications_not_declared": ConnectProblemBase & {
    code: "notifications_not_declared";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
  "notifications_unavailable": ConnectProblemBase & {
    code: "notifications_unavailable";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "operation_cancelled": ConnectProblemBase & {
    code: "operation_cancelled";
    category: "cancellation";
    recovery: "none";
    details?: never;
  };
  "operation_failed": ConnectProblemBase & {
    code: "operation_failed";
    category: "internal";
    recovery: "contact_support";
    details?: never;
  };
  "operation_invalid": ConnectProblemBase & {
    code: "operation_invalid";
    category: "validation";
    recovery: "fix_request";
    details: ConnectProblemDetailsByCode["operation_invalid"];
  };
  "operation_outcome_unknown": ConnectProblemBase & {
    code: "operation_outcome_unknown";
    category: "conflict";
    recovery: "resolve_outcome";
    details: ConnectProblemDetailsByCode["operation_outcome_unknown"];
  };
  "path_occupied": ConnectProblemBase & {
    code: "path_occupied";
    category: "conflict";
    recovery: "resolve_conflict";
    details?: never;
  };
  "pending_mutation_unresolved": ConnectProblemBase & {
    code: "pending_mutation_unresolved";
    category: "conflict";
    recovery: "resolve_outcome";
    details?: never;
  };
  "query_snapshot_changed": ConnectProblemBase & {
    code: "query_snapshot_changed";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "rate_limited": ConnectProblemBase & {
    code: "rate_limited";
    category: "availability";
    recovery: "retry";
    details?: ConnectProblemDetailsByCode["rate_limited"];
  };
  "reconnect_required": ConnectProblemBase & {
    code: "reconnect_required";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "redirect_uri_required": ConnectProblemBase & {
    code: "redirect_uri_required";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "reference_updates_unsupported": ConnectProblemBase & {
    code: "reference_updates_unsupported";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
  "registry_backup_invalid": ConnectProblemBase & {
    code: "registry_backup_invalid";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "registry_busy": ConnectProblemBase & {
    code: "registry_busy";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "registry_corrupt": ConnectProblemBase & {
    code: "registry_corrupt";
    category: "integrity";
    recovery: "repair_collection";
    details?: never;
  };
  "registry_migration_failed": ConnectProblemBase & {
    code: "registry_migration_failed";
    category: "internal";
    recovery: "contact_support";
    details?: never;
  };
  "registry_schema_incompatible": ConnectProblemBase & {
    code: "registry_schema_incompatible";
    category: "compatibility";
    recovery: "upgrade_connector";
    details?: never;
  };
  "relay_authorization_expired": ConnectProblemBase & {
    code: "relay_authorization_expired";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "relay_unavailable": ConnectProblemBase & {
    code: "relay_unavailable";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "sandbox_unsupported": ConnectProblemBase & {
    code: "sandbox_unsupported";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
  "scope_denied": ConnectProblemBase & {
    code: "scope_denied";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "stale_file_revision": ConnectProblemBase & {
    code: "stale_file_revision";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "storage_required": ConnectProblemBase & {
    code: "storage_required";
    category: "compatibility";
    recovery: "none";
    details?: never;
  };
  "sync_failed": ConnectProblemBase & {
    code: "sync_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "temporarily_unavailable": ConnectProblemBase & {
    code: "temporarily_unavailable";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "timeout": ConnectProblemBase & {
    code: "timeout";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "token_exchange_failed": ConnectProblemBase & {
    code: "token_exchange_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "transport_protocol_incompatible": ConnectProblemBase & {
    code: "transport_protocol_incompatible";
    category: "compatibility";
    recovery: "upgrade_connector";
    details: ConnectProblemDetailsByCode["transport_protocol_incompatible"];
  };
  "type_pack_provision_failed": ConnectProblemBase & {
    code: "type_pack_provision_failed";
    category: "validation";
    recovery: "repair_collection";
    details?: never;
  };
  "unknown_collection": ConnectProblemBase & {
    code: "unknown_collection";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "unsafe_file_path": ConnectProblemBase & {
    code: "unsafe_file_path";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "unsupported_encryption": ConnectProblemBase & {
    code: "unsupported_encryption";
    category: "compatibility";
    recovery: "upgrade_application";
    details?: never;
  };
  "unsupported_operation": ConnectProblemBase & {
    code: "unsupported_operation";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
}

export type KnownConnectProblem<Code extends ConnectProblemCode = ConnectProblemCode> = ConnectProblemByCode[Code];

export type UnknownConnectProblem = ConnectProblemBase & {
  code: "unknown";
  server_code: string;
  category: "unknown";
  recovery: "none";
  details?: unknown;
};

export type ConnectProblem<Code extends ConnectProblemCode = ConnectProblemCode> = KnownConnectProblem<Code> | UnknownConnectProblem;

type ConnectProblemDetailSchema = {
  type?: "string" | "integer" | "number" | "boolean" | "array" | "object";
  required?: readonly string[];
  properties?: Readonly<Record<string, ConnectProblemDetailSchema>>;
  items?: ConnectProblemDetailSchema;
};

const CONNECT_PROBLEM_DETAIL_SCHEMAS: Readonly<Record<string, ConnectProblemDetailSchema>> = {
  "access_denied": {
    "type": "object",
    "required": [],
    "properties": {
      "return_to": {
        "type": "string"
      }
    }
  },
  "approval_window_blocked": {
    "type": "object",
    "required": [
      "user_code",
      "verification_uri",
      "verification_uri_complete",
      "expires_at",
      "interval_seconds"
    ],
    "properties": {
      "user_code": {
        "type": "string"
      },
      "verification_uri": {
        "type": "string"
      },
      "verification_uri_complete": {
        "type": "string"
      },
      "expires_at": {
        "type": "integer"
      },
      "interval_seconds": {
        "type": "integer"
      }
    }
  },
  "authorization_binding_incompatible": {
    "type": "object",
    "required": [
      "contract",
      "required",
      "supported",
      "peer"
    ],
    "properties": {
      "contract": {
        "type": "string"
      },
      "required": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "supported": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "peer": {
        "type": "string"
      },
      "operation": {
        "type": "string"
      }
    }
  },
  "capability_contract_incompatible": {
    "type": "object",
    "required": [
      "contract",
      "required",
      "supported",
      "peer"
    ],
    "properties": {
      "contract": {
        "type": "string"
      },
      "required": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "supported": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "peer": {
        "type": "string"
      },
      "operation": {
        "type": "string"
      }
    }
  },
  "collection_configuration_invalid": {
    "type": "object",
    "required": [
      "diagnostics"
    ],
    "properties": {
      "diagnostics": {
        "type": "array",
        "items": {
          "type": "object"
        }
      }
    }
  },
  "collection_contracts_missing": {
    "type": "object",
    "required": [
      "contracts"
    ],
    "properties": {
      "contracts": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "id",
            "version"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "collection_invalid": {
    "type": "object",
    "required": [
      "diagnostics"
    ],
    "properties": {
      "diagnostics": {
        "type": "array",
        "items": {
          "type": "object"
        }
      }
    }
  },
  "collection_type_registry_invalid": {
    "type": "object",
    "required": [
      "diagnostics"
    ],
    "properties": {
      "diagnostics": {
        "type": "array",
        "items": {
          "type": "object"
        }
      }
    }
  },
  "collection_version_unsupported": {
    "type": "object",
    "required": [
      "current_version",
      "required_version"
    ],
    "properties": {
      "current_version": {
        "type": "string"
      },
      "required_version": {
        "type": "string"
      }
    }
  },
  "connector_offline": {
    "type": "object",
    "required": [],
    "properties": {
      "connector_name": {
        "type": "string"
      }
    }
  },
  "durable_mutation_unsupported": {
    "type": "object",
    "required": [
      "contract",
      "required",
      "supported",
      "peer"
    ],
    "properties": {
      "contract": {
        "type": "string"
      },
      "required": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "supported": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "peer": {
        "type": "string"
      },
      "operation": {
        "type": "string"
      }
    }
  },
  "insufficient_access": {
    "type": "object",
    "required": [
      "required_operations",
      "granted_operations",
      "missing_operations"
    ],
    "properties": {
      "required_operations": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "granted_operations": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "missing_operations": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
  "invalid_application_manifest": {
    "type": "object",
    "required": [
      "issues"
    ],
    "properties": {
      "issues": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "path",
            "keyword",
            "message",
            "params"
          ],
          "properties": {
            "path": {
              "type": "string"
            },
            "keyword": {
              "type": "string"
            },
            "message": {
              "type": "string"
            },
            "params": {
              "type": "object"
            }
          }
        }
      }
    }
  },
  "mutation_request_conflict": {
    "type": "object",
    "required": [
      "request_id"
    ],
    "properties": {
      "request_id": {
        "type": "string"
      }
    }
  },
  "operation_invalid": {
    "type": "object",
    "required": [
      "diagnostics"
    ],
    "properties": {
      "diagnostics": {
        "type": "array",
        "items": {
          "type": "object"
        }
      },
      "partial_result": {}
    }
  },
  "operation_outcome_unknown": {
    "type": "object",
    "required": [
      "request_id"
    ],
    "properties": {
      "request_id": {
        "type": "string"
      }
    }
  },
  "rate_limited": {
    "type": "object",
    "required": [],
    "properties": {
      "retry_after_ms": {
        "type": "integer"
      }
    }
  },
  "transport_protocol_incompatible": {
    "type": "object",
    "required": [
      "contract",
      "required",
      "supported",
      "peer"
    ],
    "properties": {
      "contract": {
        "type": "string"
      },
      "required": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "supported": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "peer": {
        "type": "string"
      },
      "operation": {
        "type": "string"
      }
    }
  }
};

export function isConnectProblemCode(code: string): code is ConnectProblemCode {
  return Object.hasOwn(CONNECT_PROBLEM_CATALOG, code);
}

export function isConnectProblem(value: unknown): value is ConnectProblem {
  if (!isPlainObject(value)) return false;
  const candidate = value as Record<string, unknown>;
  if (candidate.problem_version !== CONNECT_PROBLEM_VERSION || typeof candidate.message !== "string" || candidate.message.length === 0) return false;
  if (candidate.operation_outcome !== undefined && candidate.operation_outcome !== "not_sent" && candidate.operation_outcome !== "rejected" && candidate.operation_outcome !== "unknown") return false;
  if (candidate.trace_id !== undefined && (typeof candidate.trace_id !== "string" || candidate.trace_id.length === 0)) return false;
  if (candidate.code === "unknown") {
    return typeof candidate.server_code === "string"
      && candidate.server_code.length > 0
      && candidate.category === "unknown"
      && candidate.recovery === "none";
  }
  if (typeof candidate.code !== "string" || !isConnectProblemCode(candidate.code) || candidate.server_code !== undefined) return false;
  const definition = CONNECT_PROBLEM_CATALOG[candidate.code];
  const detailsSchema = CONNECT_PROBLEM_DETAIL_SCHEMAS[candidate.code];
  const detailsMatch = detailsSchema === undefined
    ? candidate.details === undefined
    : candidate.details === undefined
      ? (detailsSchema.required?.length ?? 0) === 0
      : matchesDetailSchema(candidate.details, detailsSchema);
  return candidate.category === definition.category
    && candidate.recovery === definition.recovery
    && detailsMatch;
}

function matchesDetailSchema(value: unknown, schema: ConnectProblemDetailSchema): boolean {
  if (schema.type === undefined) return true;
  if (schema.type === "string") return typeof value === "string";
  if (schema.type === "integer") return typeof value === "number" && Number.isInteger(value);
  if (schema.type === "number") return typeof value === "number" && Number.isFinite(value);
  if (schema.type === "boolean") return typeof value === "boolean";
  if (schema.type === "array") return Array.isArray(value) && value.every((item) => matchesDetailSchema(item, schema.items ?? {}));
  if (!isPlainObject(value)) return false;
  if (!schema.properties) return true;
  const candidate = value as Record<string, unknown>;
  if (!Object.keys(candidate).every((key) => Object.hasOwn(schema.properties!, key))) return false;
  if (!(schema.required ?? []).every((key) => Object.hasOwn(candidate, key))) return false;
  return Object.entries(candidate).every(([key, item]) => matchesDetailSchema(item, schema.properties![key]!));
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

export function normalizeConnectProblem(
  serverCode: string,
  message: string,
  options: { details?: unknown; operation_outcome?: ConnectOperationOutcome; trace_id?: string } = {}
): ConnectProblem {
  if (isConnectProblemCode(serverCode)) {
    const definition = CONNECT_PROBLEM_CATALOG[serverCode];
    const candidate = {
      problem_version: CONNECT_PROBLEM_VERSION,
      code: serverCode,
      category: definition.category,
      recovery: definition.recovery,
      message,
      ...(options.details === undefined ? {} : { details: options.details }),
      ...(options.operation_outcome === undefined ? {} : { operation_outcome: options.operation_outcome }),
      ...(options.trace_id === undefined ? {} : { trace_id: options.trace_id })
    };
    if (isConnectProblem(candidate)) return candidate;
  }
  return {
    problem_version: CONNECT_PROBLEM_VERSION,
    code: "unknown",
    server_code: serverCode,
    category: "unknown",
    recovery: "none",
    message,
    ...(options.details === undefined ? {} : { details: options.details }),
    ...(options.operation_outcome === undefined ? {} : { operation_outcome: options.operation_outcome }),
    ...(options.trace_id === undefined ? {} : { trace_id: options.trace_id })
  };
}
