// Generated by scripts/generate-connect-problems.mjs. Do not edit directly.

export const CONNECT_PROBLEM_VERSION = 1 as const;

export const CONNECT_PROBLEM_CATALOG = {
  "approval_window_blocked": { category: "authorization", recovery: "reauthorize" },
  "authority_authorization_changed": { category: "authorization", recovery: "reauthorize" },
  "authorization_cancelled": { category: "cancellation", recovery: "none" },
  "authorization_expired": { category: "authorization", recovery: "reauthorize" },
  "browser_required": { category: "compatibility", recovery: "none" },
  "callback_url_required": { category: "validation", recovery: "fix_request" },
  "change_cursor_reset": { category: "conflict", recovery: "refresh" },
  "collection_access_denied": { category: "authorization", recovery: "reauthorize" },
  "collection_configuration_invalid": { category: "validation", recovery: "repair_collection" },
  "collection_contracts_missing": { category: "compatibility", recovery: "choose_collection" },
  "collection_incompatible": { category: "compatibility", recovery: "choose_collection" },
  "collection_invalid": { category: "validation", recovery: "repair_collection" },
  "collection_kind_unsupported": { category: "compatibility", recovery: "choose_collection" },
  "collection_mismatch": { category: "selection", recovery: "choose_collection" },
  "collection_not_found": { category: "selection", recovery: "choose_collection" },
  "collection_not_ready": { category: "selection", recovery: "choose_collection" },
  "collection_not_selected": { category: "selection", recovery: "choose_collection" },
  "collection_type_registry_invalid": { category: "validation", recovery: "repair_collection" },
  "collection_version_unsupported": { category: "compatibility", recovery: "upgrade_collection" },
  "concurrent_modification": { category: "conflict", recovery: "refresh" },
  "connector_identity_changed": { category: "integrity", recovery: "reauthorize" },
  "connector_offline": { category: "availability", recovery: "retry" },
  "connector_upgrade_required": { category: "compatibility", recovery: "upgrade_connector" },
  "device_authorization_failed": { category: "authorization", recovery: "reauthorize" },
  "direct_operation_rejected": { category: "authorization", recovery: "reauthorize" },
  "direct_outcome_unknown": { category: "conflict", recovery: "resolve_outcome" },
  "discovery_failed": { category: "availability", recovery: "retry" },
  "encryption_required": { category: "authorization", recovery: "reauthorize" },
  "expired_token": { category: "authorization", recovery: "reauthorize" },
  "hosted_provider_unavailable": { category: "availability", recovery: "retry" },
  "insufficient_access": { category: "authorization", recovery: "reauthorize" },
  "invalid_application_manifest": { category: "validation", recovery: "fix_request" },
  "invalid_callback": { category: "validation", recovery: "fix_request" },
  "invalid_device_authorization_response": { category: "integrity", recovery: "contact_support" },
  "invalid_encrypted_response": { category: "integrity", recovery: "contact_support" },
  "invalid_loopback_url": { category: "validation", recovery: "fix_request" },
  "invalid_operation_response": { category: "integrity", recovery: "contact_support" },
  "invalid_path": { category: "validation", recovery: "fix_request" },
  "invalid_preflight": { category: "conflict", recovery: "refresh" },
  "invalid_push_payload": { category: "validation", recovery: "fix_request" },
  "invalid_push_subscription": { category: "validation", recovery: "fix_request" },
  "invalid_request": { category: "validation", recovery: "fix_request" },
  "invalid_token_response": { category: "integrity", recovery: "contact_support" },
  "managed_fcm_not_declared": { category: "compatibility", recovery: "fix_request" },
  "manifest_load_failed": { category: "availability", recovery: "retry" },
  "manifest_required": { category: "validation", recovery: "fix_request" },
  "missing_grant_key": { category: "authorization", recovery: "reauthorize" },
  "no_pending_mutation": { category: "conflict", recovery: "refresh" },
  "not_authorized": { category: "authorization", recovery: "reauthorize" },
  "not_remote_authority": { category: "compatibility", recovery: "choose_collection" },
  "notification_criterion_not_declared": { category: "validation", recovery: "fix_request" },
  "notification_reauthorization_required": { category: "authorization", recovery: "reauthorize" },
  "notification_registration_failed": { category: "availability", recovery: "retry" },
  "notification_unregistration_failed": { category: "availability", recovery: "retry" },
  "notifications_not_declared": { category: "compatibility", recovery: "fix_request" },
  "notifications_unavailable": { category: "availability", recovery: "retry" },
  "operation_cancelled": { category: "cancellation", recovery: "none" },
  "operation_failed": { category: "internal", recovery: "contact_support" },
  "operation_invalid": { category: "validation", recovery: "fix_request" },
  "pending_mutation_unresolved": { category: "conflict", recovery: "resolve_outcome" },
  "query_snapshot_changed": { category: "conflict", recovery: "refresh" },
  "rate_limited": { category: "availability", recovery: "retry" },
  "relay_authorization_expired": { category: "authorization", recovery: "reauthorize" },
  "relay_unavailable": { category: "availability", recovery: "retry" },
  "sandbox_unsupported": { category: "compatibility", recovery: "fix_request" },
  "scope_denied": { category: "authorization", recovery: "reauthorize" },
  "storage_required": { category: "compatibility", recovery: "none" },
  "sync_failed": { category: "availability", recovery: "retry" },
  "temporarily_unavailable": { category: "availability", recovery: "retry" },
  "timeout": { category: "availability", recovery: "retry" },
  "token_exchange_failed": { category: "availability", recovery: "retry" },
  "type_pack_provision_failed": { category: "validation", recovery: "repair_collection" },
  "unknown_collection": { category: "selection", recovery: "choose_collection" },
  "unsupported_encryption": { category: "compatibility", recovery: "upgrade_application" },
  "unsupported_operation": { category: "compatibility", recovery: "fix_request" }
} as const;

export type ConnectProblemCode = keyof typeof CONNECT_PROBLEM_CATALOG;
export type ConnectProblemCategory = "authorization" | "availability" | "cancellation" | "compatibility" | "conflict" | "integrity" | "internal" | "selection" | "validation" | "unknown";
export type ConnectRecoveryAction = "choose_collection" | "contact_support" | "fix_request" | "none" | "reauthorize" | "refresh" | "repair_collection" | "resolve_conflict" | "resolve_outcome" | "retry" | "upgrade_application" | "upgrade_collection" | "upgrade_connector";
export type ConnectOperationOutcome = "not_sent" | "rejected" | "unknown";

export interface ConnectProblemBase {
  problem_version: typeof CONNECT_PROBLEM_VERSION;
  message: string;
  operation_outcome?: ConnectOperationOutcome;
  trace_id?: string;
}

export interface ConnectProblemDetailsByCode {
  "approval_window_blocked": undefined;
  "authority_authorization_changed": undefined;
  "authorization_cancelled": undefined;
  "authorization_expired": undefined;
  "browser_required": undefined;
  "callback_url_required": undefined;
  "change_cursor_reset": undefined;
  "collection_access_denied": undefined;
  "collection_configuration_invalid": {
  "diagnostics": Array<Record<string, unknown>>;
};
  "collection_contracts_missing": {
  "contracts": Array<{
    "id": string;
    "version": string;
  }>;
};
  "collection_incompatible": undefined;
  "collection_invalid": {
  "diagnostics": Array<Record<string, unknown>>;
};
  "collection_kind_unsupported": undefined;
  "collection_mismatch": undefined;
  "collection_not_found": undefined;
  "collection_not_ready": undefined;
  "collection_not_selected": undefined;
  "collection_type_registry_invalid": {
  "diagnostics": Array<Record<string, unknown>>;
};
  "collection_version_unsupported": {
  "current_version": string;
  "required_version": string;
};
  "concurrent_modification": undefined;
  "connector_identity_changed": undefined;
  "connector_offline": {
  "connector_name"?: string;
};
  "connector_upgrade_required": undefined;
  "device_authorization_failed": undefined;
  "direct_operation_rejected": undefined;
  "direct_outcome_unknown": undefined;
  "discovery_failed": undefined;
  "encryption_required": undefined;
  "expired_token": undefined;
  "hosted_provider_unavailable": undefined;
  "insufficient_access": {
  "required_operations": Array<string>;
  "granted_operations": Array<string>;
  "missing_operations": Array<string>;
};
  "invalid_application_manifest": undefined;
  "invalid_callback": undefined;
  "invalid_device_authorization_response": undefined;
  "invalid_encrypted_response": undefined;
  "invalid_loopback_url": undefined;
  "invalid_operation_response": undefined;
  "invalid_path": undefined;
  "invalid_preflight": undefined;
  "invalid_push_payload": undefined;
  "invalid_push_subscription": undefined;
  "invalid_request": undefined;
  "invalid_token_response": undefined;
  "managed_fcm_not_declared": undefined;
  "manifest_load_failed": undefined;
  "manifest_required": undefined;
  "missing_grant_key": undefined;
  "no_pending_mutation": undefined;
  "not_authorized": undefined;
  "not_remote_authority": undefined;
  "notification_criterion_not_declared": undefined;
  "notification_reauthorization_required": undefined;
  "notification_registration_failed": undefined;
  "notification_unregistration_failed": undefined;
  "notifications_not_declared": undefined;
  "notifications_unavailable": undefined;
  "operation_cancelled": undefined;
  "operation_failed": undefined;
  "operation_invalid": {
  "diagnostics": Array<Record<string, unknown>>;
  "partial_result"?: unknown;
};
  "pending_mutation_unresolved": undefined;
  "query_snapshot_changed": undefined;
  "rate_limited": {
  "retry_after_ms"?: number;
};
  "relay_authorization_expired": undefined;
  "relay_unavailable": undefined;
  "sandbox_unsupported": undefined;
  "scope_denied": undefined;
  "storage_required": undefined;
  "sync_failed": undefined;
  "temporarily_unavailable": undefined;
  "timeout": undefined;
  "token_exchange_failed": undefined;
  "type_pack_provision_failed": undefined;
  "unknown_collection": undefined;
  "unsupported_encryption": undefined;
  "unsupported_operation": undefined;
}

export interface ConnectProblemByCode {
  "approval_window_blocked": ConnectProblemBase & {
    code: "approval_window_blocked";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "authority_authorization_changed": ConnectProblemBase & {
    code: "authority_authorization_changed";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "authorization_cancelled": ConnectProblemBase & {
    code: "authorization_cancelled";
    category: "cancellation";
    recovery: "none";
    details?: never;
  };
  "authorization_expired": ConnectProblemBase & {
    code: "authorization_expired";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "browser_required": ConnectProblemBase & {
    code: "browser_required";
    category: "compatibility";
    recovery: "none";
    details?: never;
  };
  "callback_url_required": ConnectProblemBase & {
    code: "callback_url_required";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "change_cursor_reset": ConnectProblemBase & {
    code: "change_cursor_reset";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "collection_access_denied": ConnectProblemBase & {
    code: "collection_access_denied";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "collection_configuration_invalid": ConnectProblemBase & {
    code: "collection_configuration_invalid";
    category: "validation";
    recovery: "repair_collection";
    details: ConnectProblemDetailsByCode["collection_configuration_invalid"];
  };
  "collection_contracts_missing": ConnectProblemBase & {
    code: "collection_contracts_missing";
    category: "compatibility";
    recovery: "choose_collection";
    details: ConnectProblemDetailsByCode["collection_contracts_missing"];
  };
  "collection_incompatible": ConnectProblemBase & {
    code: "collection_incompatible";
    category: "compatibility";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_invalid": ConnectProblemBase & {
    code: "collection_invalid";
    category: "validation";
    recovery: "repair_collection";
    details: ConnectProblemDetailsByCode["collection_invalid"];
  };
  "collection_kind_unsupported": ConnectProblemBase & {
    code: "collection_kind_unsupported";
    category: "compatibility";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_mismatch": ConnectProblemBase & {
    code: "collection_mismatch";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_not_found": ConnectProblemBase & {
    code: "collection_not_found";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_not_ready": ConnectProblemBase & {
    code: "collection_not_ready";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_not_selected": ConnectProblemBase & {
    code: "collection_not_selected";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "collection_type_registry_invalid": ConnectProblemBase & {
    code: "collection_type_registry_invalid";
    category: "validation";
    recovery: "repair_collection";
    details: ConnectProblemDetailsByCode["collection_type_registry_invalid"];
  };
  "collection_version_unsupported": ConnectProblemBase & {
    code: "collection_version_unsupported";
    category: "compatibility";
    recovery: "upgrade_collection";
    details: ConnectProblemDetailsByCode["collection_version_unsupported"];
  };
  "concurrent_modification": ConnectProblemBase & {
    code: "concurrent_modification";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "connector_identity_changed": ConnectProblemBase & {
    code: "connector_identity_changed";
    category: "integrity";
    recovery: "reauthorize";
    details?: never;
  };
  "connector_offline": ConnectProblemBase & {
    code: "connector_offline";
    category: "availability";
    recovery: "retry";
    details?: ConnectProblemDetailsByCode["connector_offline"];
  };
  "connector_upgrade_required": ConnectProblemBase & {
    code: "connector_upgrade_required";
    category: "compatibility";
    recovery: "upgrade_connector";
    details?: never;
  };
  "device_authorization_failed": ConnectProblemBase & {
    code: "device_authorization_failed";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "direct_operation_rejected": ConnectProblemBase & {
    code: "direct_operation_rejected";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "direct_outcome_unknown": ConnectProblemBase & {
    code: "direct_outcome_unknown";
    category: "conflict";
    recovery: "resolve_outcome";
    details?: never;
  };
  "discovery_failed": ConnectProblemBase & {
    code: "discovery_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "encryption_required": ConnectProblemBase & {
    code: "encryption_required";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "expired_token": ConnectProblemBase & {
    code: "expired_token";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "hosted_provider_unavailable": ConnectProblemBase & {
    code: "hosted_provider_unavailable";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "insufficient_access": ConnectProblemBase & {
    code: "insufficient_access";
    category: "authorization";
    recovery: "reauthorize";
    details: ConnectProblemDetailsByCode["insufficient_access"];
  };
  "invalid_application_manifest": ConnectProblemBase & {
    code: "invalid_application_manifest";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_callback": ConnectProblemBase & {
    code: "invalid_callback";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_device_authorization_response": ConnectProblemBase & {
    code: "invalid_device_authorization_response";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "invalid_encrypted_response": ConnectProblemBase & {
    code: "invalid_encrypted_response";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "invalid_loopback_url": ConnectProblemBase & {
    code: "invalid_loopback_url";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_operation_response": ConnectProblemBase & {
    code: "invalid_operation_response";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "invalid_path": ConnectProblemBase & {
    code: "invalid_path";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_preflight": ConnectProblemBase & {
    code: "invalid_preflight";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "invalid_push_payload": ConnectProblemBase & {
    code: "invalid_push_payload";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_push_subscription": ConnectProblemBase & {
    code: "invalid_push_subscription";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_request": ConnectProblemBase & {
    code: "invalid_request";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "invalid_token_response": ConnectProblemBase & {
    code: "invalid_token_response";
    category: "integrity";
    recovery: "contact_support";
    details?: never;
  };
  "managed_fcm_not_declared": ConnectProblemBase & {
    code: "managed_fcm_not_declared";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
  "manifest_load_failed": ConnectProblemBase & {
    code: "manifest_load_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "manifest_required": ConnectProblemBase & {
    code: "manifest_required";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "missing_grant_key": ConnectProblemBase & {
    code: "missing_grant_key";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "no_pending_mutation": ConnectProblemBase & {
    code: "no_pending_mutation";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "not_authorized": ConnectProblemBase & {
    code: "not_authorized";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "not_remote_authority": ConnectProblemBase & {
    code: "not_remote_authority";
    category: "compatibility";
    recovery: "choose_collection";
    details?: never;
  };
  "notification_criterion_not_declared": ConnectProblemBase & {
    code: "notification_criterion_not_declared";
    category: "validation";
    recovery: "fix_request";
    details?: never;
  };
  "notification_reauthorization_required": ConnectProblemBase & {
    code: "notification_reauthorization_required";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "notification_registration_failed": ConnectProblemBase & {
    code: "notification_registration_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "notification_unregistration_failed": ConnectProblemBase & {
    code: "notification_unregistration_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "notifications_not_declared": ConnectProblemBase & {
    code: "notifications_not_declared";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
  "notifications_unavailable": ConnectProblemBase & {
    code: "notifications_unavailable";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "operation_cancelled": ConnectProblemBase & {
    code: "operation_cancelled";
    category: "cancellation";
    recovery: "none";
    details?: never;
  };
  "operation_failed": ConnectProblemBase & {
    code: "operation_failed";
    category: "internal";
    recovery: "contact_support";
    details?: never;
  };
  "operation_invalid": ConnectProblemBase & {
    code: "operation_invalid";
    category: "validation";
    recovery: "fix_request";
    details: ConnectProblemDetailsByCode["operation_invalid"];
  };
  "pending_mutation_unresolved": ConnectProblemBase & {
    code: "pending_mutation_unresolved";
    category: "conflict";
    recovery: "resolve_outcome";
    details?: never;
  };
  "query_snapshot_changed": ConnectProblemBase & {
    code: "query_snapshot_changed";
    category: "conflict";
    recovery: "refresh";
    details?: never;
  };
  "rate_limited": ConnectProblemBase & {
    code: "rate_limited";
    category: "availability";
    recovery: "retry";
    details?: ConnectProblemDetailsByCode["rate_limited"];
  };
  "relay_authorization_expired": ConnectProblemBase & {
    code: "relay_authorization_expired";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "relay_unavailable": ConnectProblemBase & {
    code: "relay_unavailable";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "sandbox_unsupported": ConnectProblemBase & {
    code: "sandbox_unsupported";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
  "scope_denied": ConnectProblemBase & {
    code: "scope_denied";
    category: "authorization";
    recovery: "reauthorize";
    details?: never;
  };
  "storage_required": ConnectProblemBase & {
    code: "storage_required";
    category: "compatibility";
    recovery: "none";
    details?: never;
  };
  "sync_failed": ConnectProblemBase & {
    code: "sync_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "temporarily_unavailable": ConnectProblemBase & {
    code: "temporarily_unavailable";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "timeout": ConnectProblemBase & {
    code: "timeout";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "token_exchange_failed": ConnectProblemBase & {
    code: "token_exchange_failed";
    category: "availability";
    recovery: "retry";
    details?: never;
  };
  "type_pack_provision_failed": ConnectProblemBase & {
    code: "type_pack_provision_failed";
    category: "validation";
    recovery: "repair_collection";
    details?: never;
  };
  "unknown_collection": ConnectProblemBase & {
    code: "unknown_collection";
    category: "selection";
    recovery: "choose_collection";
    details?: never;
  };
  "unsupported_encryption": ConnectProblemBase & {
    code: "unsupported_encryption";
    category: "compatibility";
    recovery: "upgrade_application";
    details?: never;
  };
  "unsupported_operation": ConnectProblemBase & {
    code: "unsupported_operation";
    category: "compatibility";
    recovery: "fix_request";
    details?: never;
  };
}

export type KnownConnectProblem<Code extends ConnectProblemCode = ConnectProblemCode> = ConnectProblemByCode[Code];

export type UnknownConnectProblem = ConnectProblemBase & {
  code: "unknown";
  server_code: string;
  category: "unknown";
  recovery: "none";
  details?: unknown;
};

export type ConnectProblem<Code extends ConnectProblemCode = ConnectProblemCode> = KnownConnectProblem<Code> | UnknownConnectProblem;

export function isConnectProblemCode(code: string): code is ConnectProblemCode {
  return Object.hasOwn(CONNECT_PROBLEM_CATALOG, code);
}
