// mdbase runtime e2e plugin: exercises the obsidian-runtime modules inside real
// Obsidian (desktop under xvfb, Android emulator, Windows). Driven over CDP:
//   app.plugins.plugins["mdbase-runtime-e2e"].suite("<name>", opts)
// Each suite returns a JSON-able report. Acks for crash tests are logged as
// console.log("MDB-ACK", stream, n) so a driver outside the process can compare.
import { apiVersion, MarkdownView, Platform, Plugin } from "obsidian";
import {
  DeviceKeyStore,
  DualJournal,
  IdbJournalCopy,
  IndexWorkerClient,
  ObsidianEditorFence,
  VaultEvents,
  VaultJournalCopy,
  VaultPlatform,
  adapterFileIO,
  decodeAsset,
  sharedRuntime,
  tryAcquireLease,
  type FileEvent,
  type JournalEntry,
  type ObsApp,
  type RuntimeInstance,
  type SqlValue,
} from "../../../src/index.js";
// Generated by build.mjs: the worker bundle and sqlite3.wasm (base64 gzip).
import { SQLITE_WASM, WORKER_CODE } from "./generated.js";

const enc = new TextEncoder();
const dec = new TextDecoder();
const COLLECTION = "0f8e3c3a-7d2b-4c55-9d7e-0b6f3d2a1c11";
const DEVICE = "dev-e2e";
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const I = (n: number): SqlValue => ({ kind: "Integer", value: BigInt(n) });
const T = (s: string): SqlValue => ({ kind: "Text", value: s });

export default class E2EPlugin extends Plugin {
  private stop = false;

  override async onload() {
    (window as unknown as Record<string, unknown>).mdbaseE2E = this;
    // Shared runtime: every copy of this plugin registers the same runtime version.
    const slot = sharedRuntime(1);
    const info = { abiMajor: 1, runtimeVersion: "0.0.1-e2e", sem: { major: 1, minor: 0 }, serves: [{ major: 1, minor: 0 }], speaks: [{ major: 1, minor: 0 }] };
    await slot.register(this.manifest.id, info, async () => fakeRuntime(info));
  }

  override async onunload() {
    this.stop = true;
    await sharedRuntime(1).unregister(this.manifest.id);
  }

  env() {
    return { apiVersion, platform: { mobile: Platform.isMobileApp, android: Platform.isAndroidApp, ios: Platform.isIosApp }, ua: navigator.userAgent };
  }

  async suite(name: string, opts: Record<string, unknown> = {}): Promise<unknown> {
    const t0 = performance.now();
    const fn = (this as unknown as Record<string, (o: Record<string, unknown>) => Promise<unknown>>)[`s_${name}`];
    if (!fn) throw new Error(`no suite ${name}`);
    const result = await fn.call(this, opts);
    return { suite: name, env: this.env(), ms: Math.round(performance.now() - t0), result };
  }

  // ---- shared runtime ---------------------------------------------------------
  async s_shared() {
    const slot = sharedRuntime(1);
    return { versions: slot.versions(), globalKeys: Object.getOwnPropertyNames(globalThis).filter((k) => k.startsWith("__mdbase")) };
  }

  // ---- dual journal ----------------------------------------------------------
  private async journal(ns = `${COLLECTION}/${DEVICE}`, dir = `.mdbase/devices/${DEVICE}`) {
    const idb = await IdbJournalCopy.open(ns);
    const vault = new VaultJournalCopy(adapterFileIO(this.app.vault.adapter), dir, ns);
    return { j: new DualJournal([idb, vault]), idb, vault };
  }

  async s_journal(o: { n?: number }) {
    const n = o.n ?? 200;
    const ns = "e2e-basic/" + Date.now();
    const { j, idb, vault } = await this.journal(ns, `.mdbase/devices/e2e-basic-${Date.now()}`);
    await j.load();
    const stats = (xs: number[]) => {
      xs.sort((a, b) => a - b);
      return { p50: Math.round(xs[xs.length >> 1]! * 10) / 10, p95: Math.round(xs[Math.floor(xs.length * 0.95)]! * 10) / 10, max: Math.round(xs[xs.length - 1]! * 10) / 10 };
    };
    const dual: number[] = [];
    const idbOnly: number[] = [];
    const vaultOnly: number[] = [];
    const entry = (i: number) => [{ space: 1, key: enc.encode(`k${i % 50}`), version: i, value: enc.encode(`v${i}`.padEnd(300, "x")) }];
    for (let i = 1; i <= n; i++) {
      const t = performance.now();
      await j.append(entry(i));
      dual.push(performance.now() - t);
    }
    // Each copy alone, to see which dominates.
    for (let i = n + 1; i <= n + 50; i++) {
      let t = performance.now();
      await idb.append(entry(i));
      idbOnly.push(performance.now() - t);
      t = performance.now();
      await vault.append(entry(i));
      vaultOnly.push(performance.now() - t);
    }
    await j.compact([]);
    idb.close();
    return { appended: n, dual: stats(dual), idbStrict: stats(idbOnly), vaultAppend: stats(vaultOnly) };
  }

  /** Crash test: append forever, logging acks; the driver kills the app. */
  async s_journalCrashStart() {
    const { j } = await this.journal();
    const live = await j.load();
    let v = live.reduce((m, e) => Math.max(m, e.version), 0);
    this.stop = false;
    void (async () => {
      while (!this.stop) {
        v++;
        await j.append([{ space: 1, key: enc.encode(`seq`), version: v, value: enc.encode(String(v)) }, { space: 2, key: enc.encode(`k${v}`), version: v, value: enc.encode("x".repeat(200)) }]);
        console.log("MDB-ACK", "journal", v);
        if (v % 500 === 0) await j.compact((await this.snapshot(j)) ?? []);
      }
    })();
    return { startedAt: v };
  }
  private async snapshot(_j: DualJournal): Promise<JournalEntry[] | null> {
    return null; // compaction to the empty set is not what we want mid-test; skip
  }

  async s_journalCrashVerify() {
    const { j, idb } = await this.journal();
    const live = await j.load();
    const seq = live.find((e) => e.space === 1);
    const ks = live.filter((e) => e.space === 2).map((e) => Number(dec.decode(e.key).slice(1)));
    ks.sort((a, b) => a - b);
    let gaps = 0;
    for (let i = 1; i < ks.length; i++) if (ks[i] !== ks[i - 1]! + 1) gaps++;
    idb.close();
    return { seq: seq ? Number(dec.decode(seq.value!)) : 0, count: ks.length, max: ks[ks.length - 1] ?? 0, gaps, report: j.lastReport };
  }

  // ---- vault platform ----------------------------------------------------------
  async s_vault() {
    const events: FileEvent[] = [];
    let pf!: VaultPlatform;
    const app = this.app as unknown as ObsApp;
    const ev = new VaultEvents(app, (p) => pf.relPath(p), (e) => events.push(e));
    pf = new VaultPlatform(app, { root: "e2e-vault", platform: Platform, events: ev });
    ev.start();
    const out: Record<string, unknown> = { capabilities: { ...pf.capabilities, mtimeResolutionNs: String(pf.capabilities.mtimeResolutionNs) } };
    const a = this.app.vault.adapter;
    if (await a.exists("e2e-vault")) await a.rmdir("e2e-vault", true);
    await a.mkdir("e2e-vault");
    const b = (s: string) => enc.encode(s);
    const g = async (op: Parameters<VaultPlatform["perform"]>[0]) => {
      const r = await pf.perform(op);
      return r.ok ? (r.value.kind === "Guarded" ? r.value.value.kind : r.value.kind) : `err:${r.error.kind}`;
    };
    out.create = await g({ op: "GuardedCreate", path: "n/a.md", bytes: b("---\nstatus: open\n---\nbody\n") });
    out.createAgain = await g({ op: "GuardedCreate", path: "n/a.md", bytes: b("x") });
    out.createCaseVariant = await g({ op: "GuardedCreate", path: "n/A.md", bytes: b("x") });
    out.replace = await g({ op: "GuardedReplace", path: "n/a.md", expect: b("---\nstatus: open\n---\nbody\n"), new: b("---\nstatus: done\n---\nbody\n") });
    out.replaceStale = await g({ op: "GuardedReplace", path: "n/a.md", expect: b("---\nstatus: open\n---\nbody\n"), new: b("zzz") });
    out.afterReplace = await a.read("e2e-vault/n/a.md");
    await a.write("e2e-vault/bom.md", "﻿bom text");
    out.bomReplace = await g({ op: "GuardedReplace", path: "bom.md", expect: b("﻿bom text"), new: b("﻿bom done") });
    out.bomBytes = Array.from(new Uint8Array(await a.readBinary("e2e-vault/bom.md")).slice(0, 3));
    out.renameOnto = await g({ op: "RenameNoreplace", from: "bom.md", to: "n/a.md" });
    out.caseRename = await g({ op: "RenameNoreplace", from: "n/a.md", to: "n/Case.md" });
    out.caseRename2 = await g({ op: "RenameNoreplace", from: "n/Case.md", to: "n/case.md" });
    out.listing = await pf.perform({ op: "List", dir: "n" });
    out.trashStale = await g({ op: "GuardedTrash", path: "n/case.md", expect: b("nope") });
    out.trash = await g({ op: "GuardedTrash", path: "n/case.md", expect: b("---\nstatus: done\n---\nbody\n") });
    out.env = await pf.perform({ op: "Environment" });
    await sleep(300);
    ev.stop();
    out.events = events.map((e) => `${e.kind}:${e.path}${e.cookie ? `#${e.cookie}` : ""}`);
    return out;
  }

  /** Outside move pairing: the driver moves a file with the OS; we collect events. */
  async s_vaultEventsStart() {
    const events: string[] = [];
    let pf!: VaultPlatform;
    const app = this.app as unknown as ObsApp;
    const ev = new VaultEvents(app, (p) => pf.relPath(p), (e) => events.push(`${e.kind}:${e.path}${e.cookie ? `#${e.cookie}` : ""}`));
    pf = new VaultPlatform(app, { root: "e2e-move", platform: Platform, events: ev });
    ev.start();
    (window as unknown as Record<string, unknown>).mdbaseE2EEvents = { events, ev };
    return { ok: true };
  }
  async s_vaultEventsCollect() {
    const w = (window as unknown as { mdbaseE2EEvents: { events: string[]; ev: VaultEvents } }).mdbaseE2EEvents;
    w.ev.stop();
    return w.events;
  }

  // ---- editor fence -----------------------------------------------------------
  async s_fenceOpen(o: { path?: string }) {
    const path = o.path ?? "fence.md";
    if (!(await this.app.vault.adapter.exists(path))) await this.app.vault.create(path, "---\ncounter: 0\n---\n\n");
    const f = this.app.vault.getFileByPath(path)!;
    await this.app.workspace.getLeaf(false).openFile(f);
    const v = this.app.workspace.getActiveViewOfType(MarkdownView)!;
    v.editor.focus();
    v.editor.setCursor(v.editor.lastLine(), 0);
    return { open: v.file?.path, pinned: new ObsidianEditorFence(this.app.workspace as never, apiVersion).isPinned };
  }

  /**
   * Open-editor stress: the driver types; this publishes `counter: N` every 250 ms
   * through the fence (mode "fence") or through vault.process (mode "naive").
   */
  async s_fenceStress(o: { path?: string; ms?: number; mode?: "fence" | "naive" }) {
    const path = o.path ?? "fence.md";
    const fence = new ObsidianEditorFence(this.app.workspace as never, apiVersion);
    const end = performance.now() + (o.ms ?? 20000);
    let n = 0;
    const results: Record<string, number> = {};
    const lat: number[] = [];
    while (performance.now() < end) {
      n++;
      const t = performance.now();
      if (o.mode === "naive") {
        const f = this.app.vault.getFileByPath(path)!;
        await this.app.vault.process(f, (cur) => cur.replace(/counter: \d+/, `counter: ${n}`));
        results.naive = (results.naive ?? 0) + 1;
      } else {
        const v = this.app.workspace.getActiveViewOfType(MarkdownView)!;
        const buf = v.editor.getValue();
        const next = buf.replace(/counter: \d+/, `counter: ${n}`);
        const r = await fence.apply(path, buf, next);
        results[r.kind] = (results[r.kind] ?? 0) + 1;
      }
      lat.push(performance.now() - t);
      await sleep(250);
    }
    await sleep(2600); // let Obsidian's 2 s save land
    const v = this.app.workspace.getActiveViewOfType(MarkdownView);
    v?.save?.();
    await sleep(500);
    const disk = await this.app.vault.adapter.read(path);
    lat.sort((a, b) => a - b);
    return { published: n, results, finalCounter: Number(/counter: (\d+)/.exec(disk)?.[1] ?? -1), disk, p50: lat[lat.length >> 1], max: lat[lat.length - 1] };
  }

  /** Watch the disk value of counter during a stress run (regressions = went backwards). */
  async s_fenceWatch(o: { path?: string; ms?: number }) {
    const path = o.path ?? "fence.md";
    const seen: number[] = [];
    const ref = this.app.vault.on("modify", async (f) => {
      if (f.path !== path) return;
      const s = await this.app.vault.adapter.read(path);
      seen.push(Number(/counter: (\d+)/.exec(s)?.[1] ?? -1));
    });
    await sleep(o.ms ?? 23000);
    this.app.vault.offref(ref);
    let regressions = 0;
    for (let i = 1; i < seen.length; i++) if (seen[i]! < seen[i - 1]!) regressions++;
    return { samples: seen.length, regressions, last: seen[seen.length - 1] };
  }

  // ---- index -----------------------------------------------------------------
  private worker: IndexWorkerClient | null = null;
  async s_index(o: { n?: number; wipe?: boolean; collection?: string }) {
    const id = o.collection ?? COLLECTION;
    const lease = await tryAcquireLease(id);
    const t0 = performance.now();
    const wasm = await decodeAsset(SQLITE_WASM);
    const decodeMs = performance.now() - t0;
    this.worker ??= new IndexWorkerClient(WORKER_CODE);
    const t1 = performance.now();
    const info = await this.worker.open(id, wasm.buffer as ArrayBuffer, o.wipe ?? false);
    const openMs = performance.now() - t1;
    const n = o.n ?? 10000;
    const exists = await this.worker.run({ mode: "Autocommit", stmts: [{ sql: "SELECT count(*) FROM sqlite_master WHERE name='rec'", params: [] }] });
    let buildMs = 0;
    if ((exists[0]!.values[0] as { value: bigint }).value === 0n) {
      const t = performance.now();
      await this.worker.run({ mode: "Transaction", stmts: [{ sql: "CREATE TABLE rec(rid INTEGER PRIMARY KEY, path TEXT UNIQUE, status TEXT, due INTEGER)", params: [] }, { sql: "CREATE INDEX rec_status ON rec(status, due)", params: [] }] });
      for (let i = 0; i < n; i += 1000) {
        const stmts = [];
        for (let k = i; k < Math.min(n, i + 1000); k++) stmts.push({ sql: "INSERT INTO rec(path, status, due) VALUES (?, ?, ?)", params: [T(`tasks/${k}.md`), T(k % 3 ? "open" : "done"), I(k)] });
        await this.worker.run({ mode: "Transaction", stmts });
      }
      buildMs = performance.now() - t;
    }
    const tq = performance.now();
    const q = await this.worker.run({ mode: "Autocommit", stmts: [{ sql: "SELECT count(*) FROM rec WHERE status = ?", params: [T("open")] }, { sql: "SELECT path FROM rec WHERE status = ? ORDER BY due DESC LIMIT 20", params: [T("open")] }, { sql: "PRAGMA journal_mode", params: [] }, { sql: "PRAGMA locking_mode", params: [] }] });
    const queryMs = performance.now() - tq;
    return {
      lease: lease ? "held" : "busy",
      info,
      decodeMs: Math.round(decodeMs),
      openMs: Math.round(openMs),
      buildMs: Math.round(buildMs),
      queryMs: Math.round(queryMs * 10) / 10,
      openCount: Number((q[0]!.values[0] as { value: bigint }).value),
      top: q[1]!.values.length,
      journalMode: (q[2]!.values[0] as { value: string }).value,
      lockingMode: (q[3]!.values[0] as { value: string }).value,
    };
  }
  async s_indexClose() {
    await this.worker?.terminate();
    this.worker = null;
    return { closed: true };
  }
  /** A second Worker opening the same pool must fail fast with Busy. */
  async s_indexSecondOpener() {
    const wasm = await decodeAsset(SQLITE_WASM);
    const w2 = new IndexWorkerClient(WORKER_CODE);
    try {
      await w2.open(COLLECTION, wasm.buffer as ArrayBuffer);
      return { second: "opened (unexpected)" };
    } catch (e) {
      return { second: (e as { kind?: string }).kind ?? String(e) };
    } finally {
      w2.worker.terminate();
    }
  }

  // ---- keys ------------------------------------------------------------------
  async s_keys(o: { phase?: "save" | "load" }) {
    const ss = (this.app as unknown as { secretStorage?: { getSecret(id: string): string | null; setSecret(id: string, s: string): void } }).secretStorage ?? null;
    const ks = await DeviceKeyStore.open(`${COLLECTION}/${DEVICE}`, { secretStorage: ss });
    try {
      if (o.phase === "save") {
        await ks.save(new Uint8Array(96).map((_, i) => i));
        return { saved: true, protection: ks.protection };
      }
      const r = await ks.load();
      return r.kind === "present" ? { kind: r.kind, protection: r.protection, ok: r.secrets.every((x, i) => x === i) } : r;
    } finally {
      ks.close();
    }
  }
}

function fakeRuntime(info: RuntimeInstance["info"]): RuntimeInstance {
  return {
    info,
    async openHost() {},
    async closeHost() {},
    connect: () => ({ close() {} }),
    async dispose() {},
  };
}
