/** Source/tests default DENY. A deploy build MUST resolve this module alias to
 * the create-only module generated by build-release-trust.mjs after the ONE
 * shared mdbn-trust signed environment-asset verification. No runtime override. */
export interface ReleaseTrust {
  schema: "mdbn-app-trust/release/1";
  environment: "lab" | "staging" | "production";
  cpOrigin: string;
  logOrigin: string;
  assetSha256: string;
  source: { repository: string; commit: string; version: string };
  trustedRoots: readonly Uint8Array[];
  policyPins: Uint8Array;
}
export function appReleaseTrust(): ReleaseTrust | null { return null; }
