#!/usr/bin/env bash
# Concatenate the ```cddl blocks of docs/contracts/*.md into docs/contracts/wire.cddl.
# Usage: scripts/extract-cddl.sh [--check]
set -euo pipefail
cd "$(dirname "$0")/.."
out=docs/contracts/wire.cddl
tmp=$(mktemp -p "$PWD" .wire.cddl.XXXXXX)
trap 'rm -f "$tmp"' EXIT
{
  echo "; Generated by scripts/extract-cddl.sh from docs/contracts/*.md. Do not edit."
  for f in docs/contracts/00-overview.md docs/contracts/intent.md docs/contracts/log-entry.md \
           docs/contracts/sealed-envelope.md docs/contracts/snapshot.md docs/contracts/policy.md \
           docs/contracts/log-service-api.md docs/contracts/replica-client-api.md; do
    awk -v src="$f" '
      /^```cddl[[:space:]]*$/ { inblk = 1; print ""; print "; from " src; next }
      /^```[[:space:]]*$/ && inblk { inblk = 0; next }
      inblk { print }
    ' "$f"
  done
} > "$tmp"
if [[ "${1:-}" == "--check" ]]; then
  diff -u "$out" "$tmp" && echo "wire.cddl is up to date"
else
  mv "$tmp" "$out"
  echo "wrote $out"
fi
