#!/usr/bin/env python3
"""Generate crates/core/src/unicode/normalization_table.rs from the UCD.

Canonical normalization (NFC/NFD) for path keys (spec 02) and `slugify`
(spec 09), in a compact form instead of the `unicode-normalization` crate's
tables (which also carry compatibility data and cost ~136 KB of WASM).

Usage: scripts/gen-normalization-tables.py VERSION [UCD_DIR]
  UCD_DIR holds UnicodeData.txt and DerivedNormalizationProps.txt; without it
  they are downloaded from https://www.unicode.org/Public/VERSION/ucd/.
The NFC/NFD tests compare the result with the `unicode-normalization` crate
(a dev-dependency) over every code point and random strings.
"""

import hashlib
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/core/src/unicode/normalization_table.rs"


def fetch(version, name, ucd_dir):
    if ucd_dir:
        return (Path(ucd_dir) / name).read_bytes()
    return urllib.request.urlopen(f"https://www.unicode.org/Public/{version}/ucd/{name}").read()


def main() -> None:
    version = sys.argv[1]
    ucd_dir = sys.argv[2] if len(sys.argv) > 2 else None
    unicode_data = fetch(version, "UnicodeData.txt", ucd_dir)
    derived = fetch(version, "DerivedNormalizationProps.txt", ucd_dir)
    if not derived.decode().startswith(f"# DerivedNormalizationProps-{version}.txt"):
        sys.exit("version mismatch in DerivedNormalizationProps.txt")

    decomp = {}  # code -> one-step canonical mapping
    ccc = {}
    marks = set()
    for line in unicode_data.decode().splitlines():
        f = line.split(";")
        code = int(f[0], 16)
        if f[3] != "0":
            ccc[code] = int(f[3])
        if f[2] in ("Mn", "Mc", "Me"):
            marks.add(code)
        d = f[5]
        if d and not d.startswith("<"):
            decomp[code] = [int(x, 16) for x in d.split()]

    exclusions = set()
    for line in derived.decode().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        if parts[1] != "Full_Composition_Exclusion":
            continue
        lo, _, hi = parts[0].partition("..")
        for c in range(int(lo, 16), int(hi or lo, 16) + 1):
            exclusions.add(c)

    entries = []
    for code in sorted(decomp):
        m = decomp[code]
        assert len(m) in (1, 2) and all(0 < x < 1 << 21 for x in m), (hex(code), m)
        a = m[0]
        b = m[1] if len(m) == 2 else 0
        composable = len(m) == 2 and code not in exclusions
        entries.append((code, a, b, composable))
    packed = [c | (a << 21) | (b << 42) | (int(k) << 63) for c, a, b, k in entries]
    compose = sorted(
        (i for i, e in enumerate(entries) if e[3]), key=lambda i: (entries[i][1], entries[i][2])
    )
    assert len(entries) < 1 << 16

    def steps(value_of):
        out, prev = [], 0
        for c in range(0x110000):
            v = value_of(c)
            if v != prev:
                out.append((c, v))
                prev = v
        return out

    ccc_steps = steps(lambda c: ccc.get(c, 0))
    mark_steps = steps(lambda c: int(c in marks))

    major, minor, patch = (int(x) for x in version.split("."))
    digest = hashlib.sha256(unicode_data + derived).hexdigest()
    out = [
        f"// @generated by scripts/gen-normalization-tables.py from the Unicode {version}",
        f"// UnicodeData.txt and DerivedNormalizationProps.txt (sha256 {digest}).",
        "// Do not edit by hand.",
        "",
        "/// The Unicode version of these tables.",
        f"pub(super) const UNICODE_VERSION: (u8, u8, u8) = ({major}, {minor}, {patch});",
        "",
        "/// One-step canonical decompositions, sorted by code point. Each entry packs",
        "/// `code | first << 21 | second << 42 | composable << 63` (`second` is 0 for a",
        "/// singleton; `composable` marks primary composites).",
        "pub(super) static DECOMP: &[u64] = &[",
    ]
    for i in range(0, len(packed), 6):
        out.append("    " + " ".join(f"0x{p:016x}," for p in packed[i : i + 6]))
    out += [
        "];",
        "",
        "/// Indices into `DECOMP` of the primary composites, sorted by (first, second).",
        "pub(super) static COMPOSE: &[u16] = &[",
    ]
    for i in range(0, len(compose), 16):
        out.append("    " + " ".join(f"{x}," for x in compose[i : i + 16]))
    out += [
        "];",
        "",
        "/// Canonical combining class as a step function: `start << 8 | class`, the class",
        "/// applying from `start` to the next entry's start.",
        "pub(super) static CCC: &[u32] = &[",
    ]
    vals = [(c << 8) | v for c, v in ccc_steps]
    for i in range(0, len(vals), 8):
        out.append("    " + " ".join(f"0x{v:08x}," for v in vals[i : i + 8]))
    out += [
        "];",
        "",
        "/// General category M (Mn, Mc, Me) as a step function: `start << 1 | is_mark`.",
        "pub(super) static MARKS: &[u32] = &[",
    ]
    vals = [(c << 1) | v for c, v in mark_steps]
    for i in range(0, len(vals), 8):
        out.append("    " + " ".join(f"0x{v:08x}," for v in vals[i : i + 8]))
    out.append("];")
    OUT.write_text("\n".join(out) + "\n")
    size = len(packed) * 8 + len(compose) * 2 + (len(ccc_steps) + len(mark_steps)) * 4
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(packed)} decompositions, {len(compose)} composites, "
        f"{len(ccc_steps)} ccc steps, {len(mark_steps)} mark steps, ~{size} bytes"
    )


if __name__ == "__main__":
    main()
