#!/usr/bin/env python3
"""Generate the embedded, full-history IANA tzdb (no host zoneinfo reads).

Input: unpacked official tzdata2026e.tar.gz, SHA-256
b26882805f26aac59d5b222978e6580484b834ccdc98be89df2f05a6dc53a652.
Usage: python scripts/gen-tzdb-table.py /path/to/tzdata [--zic /path/to/zic]
Compiler used for this table: zic (tzcode) 2026d, -b slim.
The generated bytes, not the compiler or host tzdb, define runtime semantics.

Deduplicate alias rules, encode transition deltas/offsets as varints, and raw
DEFLATE the database. All history and POSIX future rules are retained, avoiding
silently wrong conversions outside an arbitrary 1970-2100 window.
"""
import argparse
from pathlib import Path
import struct
import subprocess
import tempfile
import zlib

RELEASE = "2026e"
ROOT = Path(__file__).resolve().parent.parent
SOURCES = "africa antarctica asia australasia europe northamerica southamerica etcetera backward".split()


def varint(n):
    assert n >= 0
    b = bytearray()
    while n >= 128:
        b.append((n & 127) | 128)
        n >>= 7
    b.append(n)
    return b


def signed(n):
    return varint(2 * n if n >= 0 else -2 * n - 1)


def encode_tzif(b):
    assert b[:5] == b"TZif2" or b[:5] == b"TZif3"
    ut, st, leap, n, k, c = struct.unpack(">6I", b[20:44])
    pos = 44 + n * 5 + k * 6 + c + leap * 8 + st + ut
    ut, st, leap, n, k, c = struct.unpack(">6I", b[pos + 20:pos + 44])
    pos += 44
    ts = struct.unpack(f">{n}q", b[pos:pos + n * 8])
    pos += n * 8
    indices = b[pos:pos + n]
    pos += n
    offsets = [struct.unpack(">i", b[pos + 6 * i:pos + 6 * i + 4])[0] for i in range(k)]
    dst = [b[pos + 6 * i + 4] for i in range(k)]
    first = next((offsets[i] for i, d in enumerate(dst) if not d), offsets[0])
    end = pos + k * 6 + c + leap * 12 + st + ut
    footer = b[end:].strip(b"\n")
    assert leap == 0 and len(footer) < 256 and n < 65536
    out = bytearray(struct.pack(">iH", first, n))
    prev = 0
    for t, i in zip(ts, indices):
        out += signed(t - prev) + signed(offsets[i])
        prev = t
    out += bytes([len(footer)]) + footer
    return bytes(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--zic", default="zic")
    args = parser.parse_args()
    assert (args.source / "version").read_text().strip() == RELEASE
    target = ROOT / "target"
    target.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="tzdb-", dir=target) as tmp:
        subprocess.run([args.zic, "-b", "slim", "-d", tmp] + [str(args.source / n) for n in SOURCES], check=True)
        rows, names = [], []
        for path in sorted(Path(tmp).rglob("*")):
            if not path.is_file():
                continue
            row = encode_tzif(path.read_bytes())
            if row not in rows:
                rows.append(row)
            names.append((path.relative_to(tmp).as_posix(), rows.index(row)))
    data = bytearray(b"MDBTZ1" + RELEASE.encode() + struct.pack(">H", len(rows)))
    for row in rows:
        data += row
    data += struct.pack(">H", len(names))
    for name, index in names:
        name = name.encode("ascii")
        assert len(name) < 256
        data += bytes([len(name)]) + name + struct.pack(">H", index)
    compressor = zlib.compressobj(9, wbits=-15)
    packed = compressor.compress(data) + compressor.flush()
    dest = ROOT / "crates/core/src/cel/time/tzdb.bin"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(packed)
    print(f"{RELEASE}: {len(names)} names, {len(rows)} rule sets; {len(data)} B -> {len(packed)} B")


if __name__ == "__main__":
    main()
