#!/usr/bin/env python3
"""Generate crates/core/src/unicode/casefold_table.rs from Unicode CaseFolding.txt.

Path keys (spec 02) use Unicode default case folding: the full mappings, i.e.
the `C` and `F` statuses of CaseFolding.txt. The table must match the Unicode
version of the NFC tables in the `unicode-normalization` crate; a unit test in
`mdbn_core::unicode` checks that the two versions agree.

Usage: scripts/gen-casefold-table.py VERSION [CaseFolding.txt]
  Without a file, downloads https://www.unicode.org/Public/VERSION/ucd/CaseFolding.txt.
"""

import hashlib
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/core/src/unicode/casefold_table.rs"


def main() -> None:
    version = sys.argv[1]
    if len(sys.argv) > 2:
        data = Path(sys.argv[2]).read_bytes()
    else:
        url = f"https://www.unicode.org/Public/{version}/ucd/CaseFolding.txt"
        data = urllib.request.urlopen(url).read()
    text = data.decode("utf-8")
    header = text.splitlines()[0]
    if header != f"# CaseFolding-{version}.txt":
        sys.exit(f"unexpected header {header!r} for version {version}")
    rows = []
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        code, status, mapping, _ = [f.strip() for f in line.split(";")]
        if status not in ("C", "F"):
            continue
        folded = "".join(chr(int(c, 16)) for c in mapping.split())
        rows.append((int(code, 16), folded))
    rows.sort()
    major, minor, patch = (int(x) for x in version.split("."))
    digest = hashlib.sha256(data).hexdigest()
    out = [
        f"// @generated by scripts/gen-casefold-table.py from CaseFolding-{version}.txt",
        f"// (sha256 {digest}). Do not edit by hand.",
        "",
        "/// The Unicode version of this table.",
        f"pub(super) const UNICODE_VERSION: (u8, u8, u8) = ({major}, {minor}, {patch});",
        "",
        "/// Full case folding (statuses C and F), sorted by code point.",
        "pub(super) static FOLD: &[(u32, &str)] = &[",
    ]
    for code, folded in rows:
        escaped = "".join(f"\\u{{{ord(c):x}}}" for c in folded)
        out.append(f'    (0x{code:x}, "{escaped}"),')
    out.append("];")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} mappings")


if __name__ == "__main__":
    main()
